erxes/erxes

- src/locales/en.json
- src/locales/mn.json
- src/modules/common/components/filter/Filter.js
- src/modules/companies/components/detail/BasicInfo.js
- src/modules/companies/components/list/CompanyForm.js
- src/modules/companies/components/list/CountsByLeadStatus.js
- src/modules/companies/components/list/Sidebar.js
- src/modules/companies/constants.js
- src/modules/companies/containers/CompaniesList.js
- src/modules/companies/graphql/queries.js
- src/modules/customers/components/index.js
- src/modules/customers/components/list/CustomerForm.js
- src/modules/customers/components/list/FormFilter.js
- src/modules/customers/components/list/LeadStatusFilter.js
- src/modules/customers/components/list/LifecycleStateFilter.js
- src/modules/customers/components/list/Sidebar.js
- src/modules/customers/constants.js
- src/modules/customers/containers/CustomersList.js
- src/modules/customers/graphql/queries.js
- src/modules/customers/utils.js
Make company list filterable by lead status
> Close #531

- src/modules/common/components/Chooser.tsx
- src/modules/companies/containers/CompanyChooser.tsx
- src/modules/customers/containers/CustomerChooser.tsx
- src/modules/customers/containers/CustomersList.tsx
- src/modules/deals/components/product/ProductItemForm.tsx
- src/modules/engage/components/EmailForm.tsx
- src/modules/engage/components/FormBase.tsx
- src/modules/engage/components/Scheduler.tsx
- src/modules/engage/components/WidgetForm.tsx
- src/modules/engage/containers/AutoAndManualForm.tsx
- src/modules/forms/components/step/CallOut.tsx
- src/modules/forms/components/step/OptionStep.tsx
- src/modules/inbox/components/conversationDetail/workarea/conversation/twitter/ModalAction.tsx
- src/modules/inbox/containers/conversationDetail/WorkArea.tsx
- src/modules/insights/components/Sidebar.tsx
- src/modules/segments/components/Condition.tsx
- src/modules/settings/email/containers/Signature.tsx
- src/modules/settings/productService/components/Form.tsx
- src/modules/settings/properties/components/ManageColumns.tsx
- src/modules/settings/properties/containers/ManageColumns.tsx
- src/modules/tags/containers/Tagger.tsx
- tslint.json
This PR fixes #615 
**Before**
```bash
yarn run tslint -c tslint.json 'src/**/*.{ts,tsx}'
ERROR: src/modules/common/components/Chooser.tsx[145, 26]: Shadowed name: 'data'
ERROR: src/modules/companies/containers/CompanyChooser.tsx[53, 17]: Shadowed name: 'props'
ERROR: src/modules/customers/containers/CustomerChooser.tsx[49, 17]: Shadowed name: 'props'
ERROR: src/modules/customers/containers/CustomersList.tsx[91, 18]: Shadowed name: 'data'
ERROR: src/modules/deals/components/product/ProductItemForm.tsx[142, 23]: Shadowed name: 'uom'
ERROR: src/modules/engage/components/EmailForm.tsx[228, 25]: Shadowed name: 'attachments'
ERROR: src/modules/engage/components/FormBase.tsx[50, 21]: Shadowed name: 'type'
ERROR: src/modules/engage/components/Scheduler.tsx[119, 31]: Shadowed name: 'type'
ERROR: …
```
> Fix disabled tslint no-shadowed-variable

- src/modules/common/components/table/styles.ts
> Table header to stay fixed when user scrolls

- src/modules/common/components/filterableList/FilterableList.tsx
> Fix uppercase filter #769

- src/modules/customers/containers/CustomersList.tsx
> Fix pagination fails in customer export #811

- src/modules/common/styles/global-styles.ts
- src/modules/inbox/components/conversationDetail/workarea/conversation/gmail/GmailConversation.tsx
- src/modules/inbox/components/conversationDetail/workarea/conversation/gmail/Mail.tsx
- src/modules/inbox/components/conversationDetail/workarea/conversation/gmail/style.ts
- src/modules/settings/integrations/components/google/MailForm.tsx
- src/modules/settings/integrations/containers/google/MailForm.tsx
Send reply email using inbox editor && resolve #870
> Gmail reply

- src/modules/companies/constants.ts
- src/modules/customers/constants.ts
- src/modules/settings/integrations/constants.ts
fixed addMessenger language, removed company and customers some options
> add messenger language fix, remove company and customers some options

- src/modules/settings/general/components/List.tsx
> Fix change language onChange bug

- src/modules/engage/styles.tsx
- src/modules/knowledgeBase/components/article/ArticleList.tsx
- src/modules/knowledgeBase/components/knowledge/KnowledgeList.tsx
> Fix engage choose time UI

- src/modules/knowledgeBase/components/knowledge/KnowledgeForm.tsx
> fix(knowledgebase): Add kb script description and additional tag

- src/modules/common/components/AnimatedLoader.tsx
- src/modules/common/components/AsyncComponent.tsx
- src/modules/common/types.ts
- src/modules/inbox/components/Inbox.tsx
- src/modules/inbox/components/conversationDetail/sidebar/Sidebar.tsx
- src/modules/inbox/components/conversationDetail/workarea/RespondBox.tsx
- src/modules/inbox/components/conversationDetail/workarea/WorkArea.tsx
- src/modules/inbox/components/leftSidebar/Sidebar.tsx
> perf(inbox): Add animated loader in inbox

- src/modules/settings/integrations/components/InstallCode.tsx
- src/modules/settings/integrations/components/common/IntegrationList.tsx
- src/modules/settings/integrations/styles.ts
- src/modules/settings/styles.ts
> Fix messenger script description

- src/modules/engage/components/FormBase.tsx
> fix(engage): Show alert when kind is auto

- src/modules/internalNotes/components/Form.tsx
> fix(editor): Fix footer buttons position

- src/modules/settings/boards/containers/Boards.tsx
- src/modules/settings/boards/containers/Pipelines.tsx
> Change remove pipeline alert message

- src/modules/settings/integrations/components/messenger/steps/Options.tsx
- src/modules/settings/integrations/styles.ts
> fix(messenger): add description in messenger toggle

- src/modules/internalNotes/components/Form.tsx
- src/modules/internalNotes/containers/Form.tsx
> fix(notes): add mutation loading in note

- src/modules/boards/components/stage/ItemList.tsx
- src/modules/boards/styles/common.ts
- src/modules/boards/styles/stage.ts
> Improve the color of the updated cards of deal / task / ticket

- src/locales/en.json
- src/locales/mn.json
- src/modules/insights/components/Chart.tsx
- src/modules/insights/components/ConversationReport.tsx
- src/modules/insights/components/ExportReport.tsx
- src/modules/insights/components/Summary.tsx
- src/modules/insights/components/TeamMembers.tsx
- src/modules/insights/constants.ts
- src/modules/insights/styles.ts
> Fix frequency report insight

- src/modules/common/components/Attachment.tsx
> fix(attachment): fix attachment view

- src/modules/activityLogs/styles.ts
> Fix broken image in activitylog

- src/modules/deals/components/product/ProductCategoryChooser.tsx
- src/modules/deals/components/product/ProductItemForm.tsx
- src/modules/deals/containers/product/ProductChooser.tsx
- src/modules/deals/styles.ts
> Add product category chooser

- src/modules/boards/components/editForm/Move.tsx
- src/modules/boards/containers/BoardSelect.tsx
> stage auto changed cancel

- src/modules/boards/components/editForm/EditForm.tsx
- src/modules/boards/types.ts
- src/modules/deals/graphql/mutations.ts
- src/modules/tasks/graphql/mutations.ts
- src/modules/tickets/graphql/mutations.ts
When deal/task/ticket is copied, then all related companies & customers will also be copied.
> copy customers & companies of deal/task/ticket

- src/modules/engage/components/EmailStatistics.tsx
- src/modules/engage/styles.tsx
- src/modules/settings/integrations/components/mail/styles.ts
> fix some styling

- ui/src/modules/customers/components/common/DetailInfo.tsx
- ui/src/modules/customers/types.ts
> Show gender, birthday in customerDetail

- widgets/client/messenger/widget/index.css
> fix popup can not cancelling

- ui/src/modules/deals/components/ProductSection.tsx
- ui/src/modules/deals/styles.ts
- widgets/client/messenger/widget/index.css
> Make it easy to navigate from the Deal edit window to the product service selection window

- ui/src/modules/deals/styles.ts
- ui/src/modules/insights/components/__tests__/__snapshots__/Chart.test.tsx.snap
https://github.com/erxes/erxes/issues/1680
> Fix style manage product service

- ui/src/modules/companies/components/common/DetailInfo.tsx
- ui/src/modules/companies/components/list/CompanyForm.tsx
- ui/src/modules/companies/graphql/mutations.ts
- ui/src/modules/companies/graphql/queries.ts
- ui/src/modules/companies/types.ts
- ui/src/modules/customers/components/list/CustomerForm.tsx
- ui/src/modules/deals/components/product/ProductForm.tsx
- ui/src/modules/deals/components/product/ProductItemForm.tsx
> Company code

- src/modules/inbox/components/conversationDetail/workarea/conversation/Conversation.tsx
[ISSUE](https://github.com/erxes/erxes/issues/1732)
> fix: check properly in conversations gmail kind

- ui/src/modules/settings/integrations/components/mail/MailForm.tsx
[ISSUE](https://github.com/erxes/erxes/issues/#1737)
Fix bug in onSubmitResolve add missing argument
> fix: send missing argument in onSubmitResolve

- .github/PULL_REQUEST_TEMPLATE.md
- ui/CHANGELOG.md
- ui/src/modules/inbox/components/conversationDetail/workarea/conversation/Conversation.tsx
[ISSUE](https://github.com/erxes/erxes/issues/1732)
Fix in conversations show the Gmail as mail.
> fix: merge with master and fix conflict

- ui/src/modules/inbox/components/conversationDetail/workarea/Editor.tsx
- ui/src/modules/inbox/components/conversationDetail/workarea/TemplateList.tsx
Draftjs based editor's (editor displayed in inbox module) embedded image rendering was broken.
> fix draft js editor image rendering

- ui/src/modules/settings/integrations/components/store/styles.ts
Increase button size for better the user experience in integration item
> ui: increase button size

- ui/src/modules/boards/containers/editForm/EditForm.tsx
[ISSUE](https://github.com/erxes/erxes/issues/1770)
> fix portable board item not found error

- README.md
> Add some new words

- CHANGELOG.md
- package.json
> fixed some typos

- ui/src/modules/settings/logs/components/LogList.tsx
- ui/src/modules/settings/logs/containers/LogList.tsx
- ui/src/modules/settings/logs/queries.ts
[ISSUE](https://github.com/erxes/erxes/issues/1807)
> add module filter to log list

- docs/docs/administrator/system-config.md
- docs/docs/developer/push-notifications.md
- docs/docs/overview/getting-started.md
- docs/docs/overview/integrations-overview.md
Update google related all docs
> update: google related docs

- ui/src/modules/engage/containers/MessageList.tsx
- ui/src/modules/engage/containers/withFormMutations.tsx
- ui/src/modules/engage/routes.tsx
- ui/src/modules/leads/containers/CreateLead.tsx
- ui/src/modules/leads/containers/EditLead.tsx
- ui/src/modules/leads/containers/List.tsx
- ui/src/modules/leads/routes.tsx
[ISSUE](https://github.com/erxes/erxes/issues/#1818)
Fix bug in engage and popup which is update list after create or edit action
> Fix list refetch

- ui/src/modules/settings/integrations/components/store/Entry.tsx
Refactor entry component to stateless function
> Refactor entry

- docs/docs/administrator/system-config.md
- ui/src/modules/settings/general/components/IntegrationConfigs.tsx
[ISSUE](https://github.com/erxes/erxes/issues/1105)
> Improvement whatsapp doc

- docs/docs/developer/contributing.md
Update contributing.md with free swag info
> Update contributing.md with Swag for Contributions

- docs/docs/user/script-install.md
Doc file of Manipulate your messenger function
> Manipulate messenger function doc

- docs/docs/administrator/system-config.md
- docs/docs/overview/integrations-overview.md
[ISSUE](https://github.com/erxes/erxes/issues/1851)
Sunshine Conversations API Docs including viber and telegram docs.
> Sunshine Conversations API Docs

- ui/src/modules/common/components/Uploader.tsx
https://github.com/erxes/erxes/issues/1875
> revert Uploader component

- docs/docs/developer/troubleshooting.md
- docs/docs/overview/getting-started.md
- docs/website/sidebars.json
> add: troubleshooting guide

- ui/src/modules/common/components/Uploader.tsx
(https://github.com/erxes/erxes/issues/1885)
> close #1885

- ui/src/modules/common/utils/uploadHandler.ts
- ui/src/modules/settings/integrations/components/mail/MailForm.tsx
- ui/src/modules/settings/integrations/containers/mail/MailForm.tsx
[Issue #1897](https://github.com/erxes/erxes/issues/#1897)
Check userId in integration for authorized file upload
> fix: add userId in uploadHandler

- widgets/client/form/containers/AppContext.tsx
[ISSUE 1900](https://github.com/erxes/erxes/issues/1900)
> hide container div after popup is closed

- .github/CODEOWNERS
- .github/workflows/documentation.yaml
- docs/website/package.json
Integrate Github Actions on our documentation website. Ref #1911
Add **CODEOWNERS** file
> docs/actions: Integrate Github Actions on our documentation website.

- docs/README.md
[1955](https://github.com/erxes/erxes/issues/1955)
https://github.com/erxes/docs moved to https://github.com/erxes/erxes
> Update Docs documentation repo

- ui/src/modules/companies/components/list/CompanyForm.tsx
- ui/src/modules/customers/constants.ts
- ui/src/modules/segments/components/common/Filter.tsx
- ui/src/modules/segments/components/common/PropertyCondition.tsx
- ui/src/modules/segments/types.ts
Add select option to the Segment property
Fixed in https://github.com/erxes/erxes/issues/1959
> perf(segment): add select options

- ui/package.json
- widgets/package.json
- widgets/yarn.lock
[#1993](https://github.com/erxes/erxes/issues/#1993)
Upgrade node-sass and package.json
> node12 compatible

- CONTRIBUTING.md
Added free swag info under Credits
> Update CONTRIBUTING.md - free swag info

- docs/docs/user/segments.md
> fixed broken img links

- ui/src/modules/settings/general/components/IntegrationConfigs.tsx
- ui/src/modules/settings/general/constants.ts
[ISSUE](https://github.com/erxes/erxes/issues/2014)
> Add facebook permission in integration config

- docs/docs/developer/developer.md
- docs/docs/overview/deployment-overview.md
[ISSUE](https://github.com/erxes/erxes/issues/2010)
Added RabbitMQ version 3.8.x+ in the prerequisites section of the developer docs.
> Added RabbitMQ in Prerequisites

- docs/docs/user/general-settings.md
General settings doc has en error.
> Update documentation on general settings

- docs/docs/installation/docker.md
> update dokcer compose to last verison

- ui/src/modules/customers/components/common/DetailInfo.tsx
- ui/src/modules/customers/components/common/PrimaryPhone.tsx
- ui/src/modules/customers/components/list/CustomerRow.tsx
- ui/src/modules/customers/graphql/queries.ts
- ui/src/modules/customers/types.ts
- ui/src/modules/settings/properties/containers/ManageColumns.tsx
[ISSUE](https://github.com/erxes/erxes/issues/2048)
> phone validation

- docs/docs/developer/developer.md
- ui/scripts/install.sh
- widgets/scripts/install.sh
[ISSUE](https://github.com/erxes/erxes/issues/2034)
Removed ```cp .env.sample .env``` from docs at https://docs.erxes.io/developer/developer/ frontend setup.
> Removed .env.sample from docs and install scripts

- ui/src/modules/boards/components/editForm/Sidebar.tsx
- ui/src/modules/boards/components/editForm/SidebarConformity.tsx
- ui/src/modules/companies/components/common/CompanySection.tsx
- ui/src/modules/conformity/containers/GetConformity.tsx
- ui/src/modules/customers/components/common/CustomerSection.tsx
[ISSUE](https://github.com/erxes/erxes/issues/2094)
> items, company, customer sidebar other element recalced fix

- ui/src/modules/engage/components/AutoAndManualForm.tsx
- ui/src/modules/engage/components/step/FullPreviewStep.tsx
- ui/src/modules/engage/styles.tsx
- ui/src/modules/leads/components/step/style.ts
- ui/src/modules/settings/integrations/constants.ts
> Fix engage

- ui/src/modules/engage/components/EngageStats.tsx
- ui/src/modules/engage/components/MessageListRow.tsx
- ui/src/modules/engage/constants.ts
- ui/src/modules/engage/containers/EngageStats.tsx
- ui/src/modules/engage/graphql/queries.ts
- ui/src/modules/engage/routes.tsx
- ui/src/modules/engage/types.ts
[ISSUE 2111](https://github.com/erxes/erxes/issues/2111)
- [+] Description is clearly stated under Context section
- [+] Screenshots and the additional verifications are attached
> shows sms stats in engage stats

- ui/src/locales/en.json
- ui/src/modules/inbox/components/ProductBoard.tsx
- ui/src/modules/inbox/components/conversationDetail/workarea/RespondBox.tsx
- ui/src/modules/inbox/containers/ProductBoard.tsx
- ui/src/modules/inbox/graphql/conversationFields.ts
- ui/src/modules/inbox/graphql/mutations.ts
- ui/src/modules/inbox/types.ts
- ui/src/modules/settings/general/components/IntegrationConfigs.tsx
- ui/src/modules/settings/general/constants.ts
[ISSUE](https://github.com/erxes/erxes/issues/2172)
> product board

- ui/src/modules/common/utils/index.tsx
- ui/src/modules/layout/components/AuthLayout.tsx
- ui/src/modules/layout/components/MainLayout.tsx
Apply basic click-jack attack defense via "iframe buster" method. As of this, erxes frontend can not be shown inside iframes.
> apply basic click-jack attack defense

- scripts/install/debian10.sh
- scripts/install/ubuntu18.sh
> Install script telemetry

- ui/src/index.tsx
- ui/src/modules/auth/components/OwnerSetup.tsx
- ui/src/modules/auth/containers/OwnerSetup.tsx
- ui/src/modules/auth/graphql/mutations.ts
- ui/src/modules/auth/types.ts
For the first time, the user needs to fill his/her email and password on the initial setup page.
> Initial setup page

- ui/src/modules/checklists/components/List.tsx
- ui/src/modules/checklists/containers/List.tsx
- ui/src/modules/checklists/graphql/mutations.ts
- ui/src/modules/checklists/styles.ts
- ui/src/modules/checklists/types.ts
- ui/src/modules/common/components/SortableList.tsx
- ui/src/modules/common/styles/sort.ts
[ISSUE](https://github.com/erxes/erxes/issues/2249)
Make checklist items sortable in Task
> Sortable checklist

- ui/src/modules/boards/components/editForm/Left.tsx
- ui/src/modules/boards/containers/editForm/EditForm.tsx
- ui/src/modules/boards/styles/item.ts
- ui/src/modules/internalNotes/components/Form.tsx
[ISSUE](https://github.com/erxes/erxes/issues/2258)
Change a textarea to the editor in the task form
> change description to editor in task form

- ui/src/index.tsx
- ui/src/modules/boards/components/editForm/Sidebar.tsx
- ui/src/modules/boards/containers/editForm/EditForm.tsx
- ui/src/modules/boards/types.ts
- ui/src/modules/common/components/Timer.tsx
- ui/src/modules/deals/options.ts
- ui/src/modules/tasks/components/TaskEditForm.tsx
- ui/src/modules/tasks/graphql/mutations.ts
- ui/src/modules/tasks/graphql/queries.ts
- ui/src/modules/tasks/options.ts
[ISSUE](https://github.com/erxes/erxes/issues/2253)
Add time tracking section for task
> Task timer

- ui/src/locales/en.json
- ui/src/modules/forms/components/FieldForm.tsx
- ui/src/modules/inbox/components/conversationDetail/workarea/conversation/messages/FormMessage.tsx
- ui/src/modules/leads/components/Lead.tsx
- ui/src/modules/leads/components/step/OptionStep.tsx
- ui/src/modules/leads/components/step/SuccessStep.tsx
- ui/src/modules/leads/types.ts
- ui/src/modules/settings/properties/components/GenerateField.tsx
- widgets/client/form/components/Field.tsx
- widgets/client/form/components/Form.tsx
- widgets/client/form/graphql.ts
- widgets/client/form/index.ts
- widgets/client/types.ts
[ISSUE](https://github.com/erxes/erxes/issues/2303)
> Popups fix

- ui/src/modules/engage/types.ts
- ui/src/modules/settings/emailDelivery/components/EmailDelivery.tsx
- ui/src/modules/settings/emailDelivery/containers/EmailDelivery.tsx
- ui/src/modules/settings/emailDelivery/queries.ts
- ui/src/modules/settings/emailDelivery/routes.tsx
- ui/src/modules/settings/main/components/Settings.tsx
- ui/src/modules/settings/routes.tsx
> add transaction emails log

- ui/src/modules/inbox/components/Resolver.tsx
- ui/src/modules/inbox/components/leftSidebar/Sidebar.tsx
- ui/src/modules/inbox/containers/Resolver.tsx
- ui/src/modules/inbox/containers/leftSidebar/Sidebar.tsx
- ui/src/modules/inbox/graphql/mutations.ts
- ui/src/modules/inbox/graphql/queries.ts
- ui/src/modules/inbox/types.ts
> Resolve all

- ui/src/modules/common/components/filter/Filter.tsx
- ui/src/modules/inbox/components/leftSidebar/StatusFilterPopover.tsx
- ui/src/modules/inbox/graphql/queries.ts
- ui/src/modules/inbox/types.ts
- ui/src/modules/inbox/utils.ts
> filter awaiting response

- ui/src/modules/customers/components/list/CustomerForm.tsx
- ui/src/modules/customers/components/list/CustomersList.tsx
- ui/src/modules/customers/constants.ts
- ui/src/modules/customers/containers/CustomersList.tsx
- ui/src/modules/customers/graphql/mutations.ts
- ui/src/modules/customers/types.ts
- ui/yarn.lock
[ISSUE](https://github.com/erxes/erxes/issues/2375)
> Force update validation status

- README.md
[ISSUE](https://github.com/erxes/erxes/issues/2369)
Fix link to Contributors
> Fix link to contributors

- docs/docs/user/contacts.md
> fixed typos

- widgets/server/index.ts
Rename health check path with more convenient word. See [more](https://microservices.io/patterns/observability/health-check-api.html).
> misc: rename health check path with more convenient word

- ui/src/modules/customers/components/common/ActionSection.tsx
- ui/src/modules/inbox/components/conversationDetail/workarea/mail/Mail.tsx
- ui/src/modules/inbox/components/conversationDetail/workarea/mail/MailConversation.tsx
- ui/src/modules/settings/integrations/containers/mail/MailForm.tsx
- ui/src/modules/settings/integrations/containers/mail/constants.ts
- ui/src/modules/settings/integrations/graphql/mutations.ts
> send mail add attribute

- ui/src/locales/en.json
- ui/src/modules/boards/components/stage/Stage.tsx
- ui/src/modules/boards/containers/Stage.tsx
[ISSUE](https://github.com/erxes/erxes/issues/2424)
Fix confirmation when archive
> fix(board): fix confirmation message when archive list. close #2424

- README.md
Closes #2415 
Closes #2414
Update links in README.md
> fix(docs): fix link to the docs start page in README

- ui/public/ckeditor/plugins/strinsert/plugin.js
- ui/src/modules/tags/containers/List.tsx
[ISSUE 1161](https://github.com/erxes/erxes/issues/1161)
Fixes: #1161
> Fix 2nd and 16th DeepCode warnings #1161

- ui/src/modules/settings/importHistory/components/Histories.tsx
[ISSUE](https://github.com/erxes/erxes/issues/2439)
> Remove localization from import&export sidebar

- api/src/__tests__/conversationDb.test.ts
- api/src/data/bulkUtils.ts
- api/src/db/models/Conversations.ts
- api/src/db/models/Engages.ts
- ui/src/modules/engage/components/MessageListRow.tsx
[ISSUE](https://github.com/erxes/erxes/issues/2432)
Now deletes conversation and conversation message when deletes engage message.
> engageMessage-remove-conversations

- ui/src/modules/settings/integrations/components/common/IntegrationListItem.tsx
External integration configuration data can now be visible at app store. Previously, it couldn't be seen elsewhere, only at creation.
> show external integration data in appstore

- api/src/__tests__/widgetMutations.test.ts
- api/src/data/resolvers/mutations/widgets.ts
- api/src/data/schema/integration.ts
- api/src/data/schema/widget.ts
- api/src/db/models/definitions/integrations.ts
- ui/src/modules/settings/integrations/components/messenger/Form.tsx
- ui/src/modules/settings/integrations/components/messenger/steps/Connection.tsx
- ui/src/modules/settings/integrations/containers/common/IntegrationForm.tsx
- ui/src/modules/settings/integrations/types.ts
- widgets/client/messenger/components/MessagesList.tsx
- widgets/client/messenger/containers/AppContext.tsx
- widgets/client/messenger/containers/ConversationDetail.tsx
- widgets/client/messenger/containers/MessagesList.tsx
- widgets/client/types.ts
[ISSUE](https://github.com/erxes/erxes/issues/2447)
Show greeting bot-message with guide
> show greetings message

- api/src/db/models/Engages.ts
- ui/src/modules/engage/components/AutoAndManualForm.tsx
[ISSUE](https://github.com/erxes/erxes/issues/2472)
> Added rule to the messenger engage 

- docs/docs/installation/aws.md
> Updated aws.md

- integrations/src/__tests__/nylasLoginMiddleware.test.ts
- integrations/src/__tests__/removeIntegration.test.ts
- integrations/src/factories.ts
- integrations/src/gmail/api.ts
- integrations/src/helpers.ts
- integrations/src/models/Accounts.ts
- integrations/src/models/Integrations.ts
- integrations/src/nylas/auth.ts
- integrations/src/nylas/controller.ts
- integrations/src/nylas/loginMiddleware.ts
[ISSUE](https://github.com/erxes/erxes/issues/2494)
Revoke Calendar/Gmail app permissions in Google
> revoke nylas google account

- api/src/cronJobs/index.ts
- api/src/cronJobs/notificatons.ts
- ui/src/modules/settings/general/components/GeneralSettings.tsx
- ui/src/modules/settings/general/constants.ts
> Notification remove cron

- ui/src/modules/settings/properties/components/GenerateField.tsx
- widgets/client/form/containers/utils.ts
[ISSUE](https://github.com/erxes/erxes/issues/2571)
Fixed the bug: An error occurred while editing custom property with date validation.
> Date property fix

- ui/src/modules/leads/components/Lead.tsx
- ui/src/modules/leads/components/step/CallOut.tsx
> Fix form callout preview

- api/src/data/utils.ts
- api/src/index.ts
Need to add an error handling for express api
> Express error handling

- ui/src/modules/engage/styles.tsx
- ui/src/modules/notifications/components/styles.ts
- Fix campaign preview height without an email template
- Fix notification scroll
> fix some style

- api/src/__tests__/engageMessageQueries.test.ts
- api/src/data/modules/coc/utils.ts
- api/src/data/resolvers/queries/engages.ts
- api/src/data/resolvers/queries/integrations.ts
- api/src/data/schema/engage.ts
- ui/src/modules/engage/graphql/queries.ts
- ui/src/modules/leads/components/List.tsx
- ui/src/modules/leads/containers/List.tsx
- ui/src/modules/leads/containers/filters/TagFilter.tsx
- ui/src/modules/leads/graphql/queries.ts
- ui/src/modules/tags/graphql/queries.ts
> Filter related tags

- api/src/__tests__/engageMessageQueries.test.ts
- api/src/db/models/Fields.ts
- ui/src/modules/settings/properties/components/GenerateField.tsx
[ISSUE](https://github.com/erxes/erxes/issues/2670)
Not able to select single number value from check box & radio button properties with options with numbers.
> Custom property fix

- api/src/__tests__/conversationMutations.test.ts
- api/src/data/resolvers/mutations/conversations.ts
- api/src/data/utils.ts
SMS conversation message longer than 160 characters were not sent. Now, it's split into chunks & sent separately.
> split long sms into chunks in conversation

- api/src/__tests__/engageMessageMutations.test.ts
- api/src/cronJobs/engages.ts
- api/src/data/resolvers/mutations/engageUtils.ts
- api/src/data/resolvers/mutations/engages.ts
- engages-email-sender/src/constants.ts
- engages-email-sender/src/sender.ts
Moved auto campaign sms limit checking from main api to engages service.
> check auto campaign sms limit inside engages

- api/src/__tests__/widgetMutations.test.ts
- api/src/data/resolvers/mutations/widgets.ts
- api/src/data/schema/integration.ts
- api/src/data/schema/widget.ts
- api/src/db/models/definitions/emailDeliveries.ts
- api/src/db/models/definitions/integrations.ts
- ui/src/modules/leads/components/Lead.tsx
- ui/src/modules/leads/components/step/SuccessStep.tsx
- ui/src/modules/leads/types.ts
- widgets/client/form/components/Form.tsx
- widgets/client/form/containers/utils.ts
- widgets/client/form/graphql.ts
- widgets/client/types.ts
[ISSUE](https://github.com/erxes/erxes/issues/2754)
> Form email attachments

- integrations/.env.sample
- integrations/src/__tests__/nylas.test.ts
- integrations/src/__tests__/nylasController.test.ts
- integrations/src/migrations/38712847182999-nylas-encypt-token.ts
- integrations/src/nylas/api.ts
- integrations/src/nylas/auth.ts
- integrations/src/nylas/handleController.ts
- integrations/src/nylas/utils.ts
> nylas encrypt token

- ui/src/modules/activityLogs/components/items/Conversation.tsx
- ui/src/modules/inbox/components/conversationDetail/workarea/conversation/styles.ts
> Attachment text

- api/src/db/models/Customers.ts
[ISSUE](https://github.com/erxes/erxes/issues/2887)
widgetsSaveCustomerGetNotified now triggers customer updated webhook action
> Improvement webhook

- api/src/__tests__/widgetMutations.test.ts
- api/src/data/resolvers/mutations/widgets.ts
- api/src/data/schema/company.ts
- api/src/data/utils.ts
- api/src/db/models/Companies.ts
- api/src/db/models/definitions/companies.ts
- api/src/middlewares/webhookMiddleware.ts
- ui/package.json
- ui/src/modules/companies/components/detail/LeftSidebar.tsx
- ui/src/modules/customers/components/common/TrackedDataSection.tsx
- ui/yarn.lock
[ISSUE](https://github.com/erxes/erxes/issues/2889)
> Company tracked data

- ui/src/modules/boards/components/RightMenu.tsx
- ui/src/modules/boards/styles/rightMenu.ts
Fixed date range in Sales Pipline
> fix date range

- ui/src/modules/dashboard/components/Home.tsx
- ui/src/modules/growthHacks/routes.tsx
- ui/src/modules/layout/components/Navigation.tsx
- ui/src/modules/layout/styles.ts
- ui/src/modules/settings/general/components/EmailConfigForm.tsx
- ui/src/pluginUtils.tsx
#comment
when expanded menu, view submenus under
> perf expanded menu

- ui/src/modules/layout/components/Navigation.tsx
#fix-bug
show tooltip text for single navigation bar
> show tooltip for single navigation bar

- ui/src/modules/boards/components/editForm/EditForm.tsx
reactivity changed color in labels
> reactivity label changecolor

- ui/src/modules/boards/containers/editForm/EditForm.tsx
> fix reactive convert to card

- ui/src/modules/boards/components/editForm/Actions.tsx
- ui/src/modules/boards/components/editForm/EditForm.tsx
- ui/src/modules/boards/components/editForm/Left.tsx
- ui/src/modules/boards/components/label/LabelChooser.tsx
- ui/src/modules/boards/components/label/Overlay.tsx
- ui/src/modules/boards/containers/label/Form.tsx
- ui/src/modules/boards/containers/label/LabelChooser.tsx
- ui/src/modules/deals/components/DealEditForm.tsx
- ui/src/modules/growthHacks/components/GrowthHackEditForm.tsx
- ui/src/modules/growthHacks/components/editForm/Actions.tsx
- ui/src/modules/tasks/components/TaskEditForm.tsx
- ui/src/modules/tickets/components/TicketEditForm.tsx
the color of the labels changes simultaneously during editing
> the color of the labels changes simultaneously during editing

- api/src/__tests__/widgetMutations.test.ts
- api/src/data/resolvers/mutations/widgets.ts
- widgets/client/form/components/Form.tsx
- widgets/client/form/graphql.ts
- widgets/client/messenger/components/Integrations.tsx
- widgets/client/messenger/containers/AppContext.tsx
- widgets/client/messenger/containers/Integrations.tsx
- widgets/client/messenger/containers/lead/LeadConnect.tsx
- widgets/client/messenger/containers/lead/LeadContent.tsx
- widgets/client/messenger/containers/lead/LeadContext.tsx
- widgets/client/types.ts
Can no longer display more than one Forms in the Messenger
> forms in the messenger

- ui/src/modules/knowledgeBase/components/knowledge/KnowledgeForm.tsx
- ui/src/modules/leads/components/step/OptionStep.tsx
- ui/src/modules/settings/integrations/components/messenger/steps/Options.tsx
https://office.erxes.io/task/board?id=wKbpQmWs3Aj7WXjc2&itemId=QTdNnSziLAFAm2zmt&key=&pipelineId=DuFAHLXpBBjSC5vn7
> perf widget selection language dropdown UI

- ui/src/modules/layout/components/Navigation.tsx
If url is in localStorage, parameter will be added to url
> Added perPage parameter to url

- ui/src/modules/layout/components/Navigation.tsx
Deleted a useless navigation named forum.
> remove useless navigation

- ui/src/modules/settings/properties/components/PropertyForm.tsx
Another part: https://github.com/erxes/erxes-ui/pull/22
Ref #2954 
Changing types:
Editing options:
Drag and drop options:
> Update type without deleting existing options

- api/src/data/resolvers/boardUtils.ts
- api/src/data/resolvers/mutations/boardUtils.ts
- api/src/data/resolvers/mutations/conformities.ts
- api/src/db/models/Checklists.ts
- api/src/db/models/Conformities.ts
- api/src/db/models/boardUtils.ts
- api/src/db/models/definitions/checklists.ts
DB calls in loops were causing `dealsCopy` mutation to run slow. There were DB calls from 2 loops and 1 nested loop. Now it's optimized not to do any DB calls from loop.
> Optimize dealsCopy mutation

- ui/src/modules/tags/components/Tagger.tsx
> show-conversation-tag-fully-additional-fixes

- ui/src/modules/boards/components/stage/ListGroupBy.tsx
- ui/src/modules/boards/components/stage/ListItemRow.tsx
- ui/src/modules/boards/styles/item.ts
- ui/src/modules/boards/styles/stage.ts
> fix some bugs

- ui/src/modules/settings/integrations/components/common/IntegrationListItem.tsx
- ui/src/modules/settings/integrations/components/webhook/Form.tsx
- ui/src/modules/settings/webhook/components/WebhookForm.tsx
For more information, please review the documentation.
> Text changed

- widgets/client/form/components/Form.tsx
[ISSUE](https://github.com/erxes/erxes/issues/3038)
> fix form logic

- ui/src/modules/boards/containers/PipelineContext.tsx
[ISSUE] solved missing parameter bug on GraphQL API.
```
_id: String! missing graphQL throws exception.
```
> fix(stageDetail,dealDetail): missing parameter error.

- api/src/__tests__/conversationDb.test.ts
- api/src/cronJobs/conversations.ts
- api/src/data/constants.ts
- api/src/data/resolvers/mutations/conversations.ts
- api/src/data/resolvers/mutations/widgets.ts
- api/src/data/resolvers/queries/logs.ts
- api/src/db/models/Conversations.ts
- api/src/db/models/definitions/conversationMessages.ts
- automations/src/controllers.ts
- automations/src/utils.ts
fix: conversation based automation refactor,  catch conversation changed event for automation trigger
> Conversation based automation

- ui/src/modules/boards/components/activityLogs/ActivityLogsByActionRow.tsx
- ui/src/modules/boards/components/activityLogs/Sidebar.tsx
- ui/src/modules/boards/constants.ts
- ui/src/modules/boards/containers/PipelineActivity.tsx
> add spinner

- api/src/__tests__/permissionQueries.test.ts
- api/src/data/permissions/actions/permission.ts
- ui/src/modules/bookings/components/Booking.tsx
- ui/src/modules/leads/components/step/SuccessStep.tsx
- widgets/client/booking/components/Product.tsx
add some new updates in booking integration.
> Booking improvement

- api/src/data/schema/integration.ts
- api/src/db/models/definitions/integrations.ts
- ui/src/modules/bookings/components/Booking.tsx
- ui/src/modules/bookings/components/steps/StyleStep.tsx
- ui/src/modules/bookings/types.ts
- ui/src/modules/inbox/components/conversationDetail/workarea/WorkArea.tsx
- ui/src/modules/settings/clientPortal/components/forms/Appearance.tsx
- ui/src/modules/settings/clientPortal/constants.ts
- widgets/client/booking/components/App.tsx
- widgets/client/booking/components/common/FilterableList.tsx
- widgets/client/booking/containers/AppContext.tsx
- widgets/client/booking/sass/components/_navigation.scss
- widgets/client/booking/sass/style.scss
- widgets/client/booking/types.ts
some refactors and booking fonts update.
> Booking widgets improvement

- api/src/__tests__/conversationQueries.test.ts
- api/src/__tests__/segments.test.ts
- api/src/data/modules/conversations/utils.ts
- api/src/data/modules/segments/queryBuilder.ts
- api/src/data/resolvers/queries/conversationQueryBuilder.ts
- api/src/data/schema/conversation.ts
- ui/src/modules/inbox/components/conversationDetail/workarea/facebook/UserName.tsx
- ui/src/modules/inbox/components/leftSidebar/Sidebar.tsx
- ui/src/modules/inbox/containers/leftSidebar/FilterToggler.tsx
- ui/src/modules/inbox/containers/leftSidebar/Sidebar.tsx
- ui/src/modules/inbox/graphql/queries.ts
- ui/src/modules/inbox/utils.ts
[office issue task link](https://office.erxes.io/task/board?id=wKbpQmWs3Aj7WXjc2&itemId=vLodsajipbK6MrhNG&key=&pipelineId=5DKrKQYKyPcMTvRXu)
> feat(inbox): segment filter with elasticsearch & display with indent implement.

- ui/src/modules/settings/properties/components/GenerateField.tsx
- ui/src/modules/settings/properties/components/PropertyForm.tsx
- ui/src/modules/settings/properties/styles.ts
> Add object list as a custom property

- api/src/__tests__/widgetQueries.test.ts
- api/src/data/resolvers/queries/widgets.ts
- api/src/data/schema/widget.ts
- widgets/client/messenger/components/ConversationDetail.tsx
- widgets/client/messenger/components/ConversationHeadContent.tsx
- widgets/client/messenger/components/ConversationInit.tsx
- widgets/client/messenger/components/Home.tsx
- widgets/client/messenger/components/Messenger.tsx
- widgets/client/messenger/components/TopBar.tsx
- widgets/client/messenger/components/common/Profile.tsx
- widgets/client/messenger/containers/AppContext.tsx
- widgets/client/messenger/containers/ConversationDetail.tsx
- widgets/client/messenger/containers/ConversationInit.tsx
- widgets/client/messenger/containers/TopBar.tsx
- widgets/client/messenger/graphql.ts
- widgets/client/messenger/sass/components/_conversations.scss
- widgets/client/messenger/sass/components/_topbar.scss
- widgets/client/types.ts
[office task link](https://office.erxes.io/task/board?id=wKbpQmWs3Aj7WXjc2&itemId=uN9jevupwarja6aFc&key=&pipelineId=x52RuXjEJ5L5ja6du)
> feat(widget): export conversations to file.

- ui/src/modules/boards/components/stage/ListGroupBy.tsx
- ui/src/modules/boards/components/stage/ListItemRow.tsx
view column products for Pipeline View option  in Deal
> view products for list view in Deal

- ui/src/modules/boards/components/MainActionBar.tsx
- ui/src/modules/boards/components/SelectType.tsx
- ui/src/modules/boards/components/activityLogs/ActivityLogs.tsx
- ui/src/modules/boards/components/chart/MainChart.tsx
- ui/src/modules/boards/constants.ts
- ui/src/modules/boards/containers/PipelineActivity.tsx
Code ReFactor for View options in List, Chart, Activity
> code refactor for view options

- api/src/data/resolvers/queries/dashboards.ts
- api/src/data/schema/dashboard.ts
- api/src/db/models/definitions/dashboard.ts
- ui/src/modules/dashboard/components/DashboardForm.tsx
- ui/src/modules/dashboard/graphql/mutations.ts
- ui/src/modules/dashboard/graphql/queries.ts
- ui/src/modules/dashboard/types.tsx
- ui/src/modules/settings/boards/components/PipelineForm.tsx
- yarn.lock
[ISSUE]
Dashboard section. Add visibility feature. Public and Private
1. When create a new dashboard, it shows public option default
2. When select private option, it shows select member. 
3. Can add multi team member
> Dashboard team member

- api/src/__tests__/dashboardDb.test.ts
add missing fields in dashboardDb test
> add missing fields in dashboardDb tests

- ui/src/modules/growthHacks/components/GrowthHackEditForm.tsx
- ui/src/modules/growthHacks/components/editForm/Top.tsx
- ui/src/modules/growthHacks/graphql/queries.ts
add number in growth hacking form and footer....
> Growth number improvement

- api/src/__tests__/engageMessageMutations.test.ts
- api/src/data/modules/segments/queryBuilder.ts
- api/src/data/resolvers/mutations/engageUtils.ts
- api/src/elasticsearch.ts
Improved elasticsearch searching so that documents more than 10000 can now be fetched in campaigns.
> add scroll feature to elk search

- packages/plugin-cards-api/src/graphql/resolvers/mutations/checklists.ts
- packages/plugin-cards-api/src/graphql/resolvers/mutations/index.ts
- packages/plugin-cards-api/src/graphql/resolvers/queries/checklists.ts
- packages/plugin-cards-api/src/graphql/resolvers/queries/index.ts
- packages/plugin-cards-api/src/graphql/schema/checklist.ts
- packages/plugin-cards-api/src/graphql/typeDefs.ts
- packages/plugin-cards-api/src/models/CheckLists.ts
- packages/plugin-cards-api/src/models/definitions/checklists.ts
- packages/plugin-cards-api/src/models/definitions/constants.ts
- packages/plugin-cards-api/src/models/index.ts
Add a Checklists in Plugin-cards-api
> add checklists in plugin-cards-api

- packages/plugin-tags-api/src/configs.ts
- packages/plugin-tags-api/src/connectionResolver.ts
- packages/plugin-tags-api/src/graphql/resolvers/mutations/tags.ts
- packages/plugin-tags-api/src/graphql/resolvers/queries/tags.ts
- packages/plugin-tags-api/src/graphql/resolvers/tags.ts
- packages/plugin-tags-api/src/logUtils.ts
- packages/plugin-tags-api/src/messageBroker.ts
- packages/plugin-tags-api/src/models/Tags.ts
- packages/plugin-tags-api/src/models/index.ts
- packages/plugin-tags-api/src/utils.ts
> Inject plugin tags api

- ui/src/modules/settings/properties/components/PropertyForm.tsx
[ISSUE](https://github.com/erxes/erxes/issues/3255)
> show validation only if the type is input

- packages/api-core/enabled-services.js
- packages/plugin-clientportal-api/src/configs.ts
- packages/plugin-clientportal-api/src/connectionResolver.ts
- packages/plugin-clientportal-api/src/graphql/resolvers/clientPortalMutations.ts
- packages/plugin-clientportal-api/src/graphql/resolvers/clientPortalQueries.ts
- packages/plugin-clientportal-api/src/messageBroker.ts
- packages/plugin-clientportal-api/src/models/ClientPortal.ts
- packages/plugin-clientportal-api/src/models/index.ts
> inject-plugiin-clientportal-api

- api/src/__tests__/productTemplateDb.test.ts
- api/src/data/resolvers/mutations/productTemplates.ts
- api/src/data/resolvers/queries/productTemplates.ts
- api/src/data/schema/productTemplate.ts
- api/src/db/factories.ts
- api/src/db/models/ProductTemplates.ts
- api/src/db/models/definitions/productTemplates.ts
- ui/src/modules/settings/templates/components/product/ProductForm.tsx
- ui/src/modules/settings/templates/components/product/ProductList.tsx
- ui/src/modules/settings/templates/components/product/ProductRow.tsx
- ui/src/modules/settings/templates/components/product/StageItem.tsx
- ui/src/modules/settings/templates/containers/product/ProductForm.tsx
- ui/src/modules/settings/templates/containers/productCategory/CategoryList.tsx
- ui/src/modules/settings/templates/graphql/mutations.ts
- ui/src/modules/settings/templates/graphql/queries.ts
- ui/src/modules/settings/templates/types.ts
Added ParentId, order, relatedIds on productLibrary
> add parentIt on product template

- packages/core-ui/src/modules/layout/components/navigation/NavigationItem.tsx
- packages/core-ui/src/modules/layout/components/navigation/NavigationListChild.tsx
- packages/core-ui/src/modules/layout/components/navigation/NavigationMore.tsx
- packages/core-ui/src/modules/layout/components/navigation/NavigationMoreItem.tsx
Fixed a bug where selecting More navigation items doesn't close the More navigation window
> fixed navigation bug + small refactor

- packages/plugin-contacts-ui/src/companies/containers/CompaniesList.tsx
- packages/plugin-contacts-ui/src/customers/containers/CustomersList.tsx
Fixed customizing table headers on contacts doesn't apply
> Issue fixed custom table headers

- packages/plugin-clientportal-api/src/models/ClientPortalUser.ts
- packages/plugin-contacts-ui/src/companies/components/list/CompaniesList.tsx
- packages/plugin-contacts-ui/src/companies/components/list/CompanyRow.tsx
- packages/plugin-contacts-ui/src/companies/containers/CompaniesList.tsx
- packages/plugin-contacts-ui/src/customers/components/list/CustomerRow.tsx
- packages/plugin-contacts-ui/src/customers/components/list/CustomersList.tsx
- packages/plugin-contacts-ui/src/customers/containers/CustomersList.tsx
- packages/plugin-tumentech-ui/src/components/list/CarRow.tsx
- packages/plugin-tumentech-ui/src/components/list/CarsList.tsx
- packages/plugin-tumentech-ui/src/containers/CarsList.tsx
- packages/ui-settings/src/properties/components/ManageColumns.tsx
add numerical index as column option to contacts list
> add numerical index as column option to contacts list

- packages/erxes-ui/src/components/ButtonMutate.tsx
- packages/plugin-inbox-ui/src/settings/integrations/components/messenger/steps/OnlineHours.tsx
> Fix little bugs

- packages/ui-cards/src/boards/components/editForm/Sidebar.tsx
- packages/ui-cards/src/boards/components/editForm/SidebarConformity.tsx
fix spacing of boxes in card detail
> fix spacing of boxes in card

- packages/plugin-inbox-ui/src/settings/integrations/components/messenger/Form.tsx
- packages/plugin-inbox-ui/src/settings/integrations/containers/messenger/Create.tsx
- packages/plugin-inbox-ui/src/settings/integrations/containers/messenger/Edit.tsx
> add loader to messenger

- packages/plugin-emailtemplates-ui/src/components/List.tsx
- packages/plugin-inbox-ui/src/forms/components/List.tsx
- packages/plugin-inbox-ui/src/forms/containers/List.tsx
- packages/ui-leads/src/graphql/queries.ts
> add searchBar to forms

- packages/core-ui/src/modules/settings/team/components/UserList.tsx
> fix doubled pagintion

- packages/core-ui/src/modules/layout/components/navigation/index.tsx
- packages/core-ui/src/modules/layout/styles.ts
Fix navigation -> Image -> width
> fix navigation image width

- packages/plugin-pos-api/src/graphql/schema/pos.ts
- packages/plugin-pos-api/src/messageBroker.ts
- packages/plugin-pos-api/src/models/definitions/pos.ts
- packages/plugin-pos-ui/src/pos/components/Pos.tsx
- packages/plugin-pos-ui/src/pos/components/cardsGroup/PerConfigs.tsx
- packages/plugin-pos-ui/src/pos/components/step/CardsConfig.tsx
- packages/plugin-pos-ui/src/pos/graphql/mutations.ts
- packages/plugin-pos-ui/src/pos/graphql/queries.ts
- packages/plugin-pos-ui/src/types.ts
> add pos sync card config

- packages/core-ui/src/modules/settings/marketplace/components/detail/Carousel.tsx
- packages/core-ui/src/modules/settings/marketplace/components/detail/PluginDetails.tsx
- packages/core-ui/src/modules/settings/marketplace/styles.tsx
> Add carousel component

- packages/plugin-ads-api/src/connectionResolver.ts
- packages/plugin-ads-api/src/graphql/resolvers/mutations/ads.ts
- packages/plugin-ads-api/src/graphql/resolvers/queries/ads.ts
- packages/plugin-ads-api/src/graphql/schema/ads.ts
- packages/plugin-ads-api/src/models/adreview.ts
- packages/plugin-ads-api/src/models/ads.ts
- packages/plugin-ads-api/src/models/definitions/adreview.ts
- packages/plugin-productreview-api/.env.sample
- packages/plugin-productreview-api/package.json
- packages/plugin-productreview-api/src/configs.ts
- packages/plugin-productreview-api/src/graphql/index.ts
- packages/plugin-productreview-api/src/graphql/resolvers/index.ts
- packages/plugin-productreview-api/src/graphql/resolvers/mutations.ts
- packages/plugin-productreview-api/src/graphql/resolvers/queries.ts
- packages/plugin-productreview-api/src/graphql/schema.ts
- packages/plugin-productreview-api/src/graphql/typeDefs.ts
- packages/plugin-productreview-api/src/messageBroker.ts
- packages/plugin-productreview-api/src/models.ts
- packages/plugin-productreview-api/tsconfig.json
> prius-center -> product review plugin, ads review

- README.md
- dashboard-ui/README.md
- docs/docs/developer/mac/deployment.md
- docs/docs/developer/mac/installation.md
- docs/docs/developer/mac/prerequisites.md
- docs/docs/developer/ubuntu/deployment.md
- docs/docs/developer/ubuntu/installation.md
- docs/docs/developer/ubuntu/prerequisites.md
- docs/docs/developer/ubuntu/server.md
- docs/docs/mac/deployment.md
- docs/docs/mac/installation.md
- docs/docs/mac/prerequisites.md
- docs/docs/ubuntu/deployment.md
- docs/docs/ubuntu/installation.md
- docs/docs/ubuntu/prerequisites.md
- docs/docs/ubuntu/server.md
- docs/sidebars.js
> Doc update

- README.md
> Updated README.md(Added Contributors Listing)

- ee/LICENSE.md
- ee/README.md
> adding license and readme

- packages/plugin-forms-api/src/graphql/schema/field.ts
- packages/plugin-forms-api/src/models/definitions/fields.ts
- packages/plugin-forms-ui/src/components/PropertyRow.tsx
- packages/ui-cards/src/boards/components/portable/GenerateAddFormFields.tsx
- packages/ui-contacts/src/customers/containers/CustomFieldsSection.tsx
- packages/ui-forms/src/settings/properties/components/GenerateCustomFields.tsx
- packages/ui-forms/src/settings/properties/components/PropertyForm.tsx
- packages/ui-forms/src/settings/properties/components/PropertyGroupForm.tsx
- packages/ui-forms/src/settings/properties/components/PropertyLogic.tsx
- packages/ui-forms/src/settings/properties/components/PropertyLogics.tsx
- packages/ui-forms/src/settings/properties/containers/PropertyLogics.tsx
- packages/ui-forms/src/settings/properties/graphql/mutations.ts
- packages/ui-forms/src/settings/properties/graphql/queries.ts
- packages/ui-forms/src/settings/properties/types.ts
- packages/ui-forms/src/settings/properties/utils.tsx
[ISSUE](https://github.com/erxes/erxes/issues/3581)
> Property group & property logics

- docs/docs/plugin-tutorials/core-plugins/clientportal.md
> update plugin tutorial docs (CLIENT PORTAL).md 

- docs/docs/plugin-tutorials/core-plugins/campaign.md
> update plugin tutorial docs (CAMPAIGN).md 

- packages/ui-cards/src/boards/components/portable/AddForm.tsx
- packages/ui-cards/src/boards/styles/item.ts
change input type of name in AddForm
> change input type of name

- packages/core/package.json
- packages/core/src/commands/migrateFields.ts
- packages/dashboard/schema/Conformities.js
- packages/dashboard/schema/Customers.js
- packages/dashboard/schema/CustomersCustomfieldsdata.js
- packages/dashboard/schema/Deals.js
- packages/dashboard/schema/Fields.js
- packages/dashboard/schema/Tasks.js
- packages/dashboard/schema/Tickets.js
- packages/plugin-dashboard-ui/src/components/dashboard/ChartRenderer.tsx
- packages/plugin-forms-api/src/connectionResolver.ts
[ISSUE] Custom fields data on Dashboard
1. Dashboard types added "Custom fields data" && you can add any filter for custom properties
2. Result
> Custom fields data dashboard

- packages/api-utils/src/segments.ts
- packages/core/src/messageBroker.ts
- packages/core/src/segments.ts
- packages/plugin-cards-api/src/segments.ts
- packages/plugin-contacts-api/src/segments.ts
- packages/plugin-forms-api/src/configs.ts
- packages/plugin-forms-api/src/segments.ts
- packages/plugin-inbox-api/src/segments.ts
- packages/plugin-segments-api/src/graphql/resolvers/queries/queryBuilder.ts
- packages/plugin-segments-api/src/graphql/resolvers/queries/segments.ts
Refactor segment's static associated types to dynamic.
> Segments type improvement

- packages/ui-forms/src/settings/properties/components/PropertyForm.tsx
> add product option to forms property type

- packages/core-ui/src/modules/settings/marketplace/components/ServiceBox.tsx
[ISSUE](https://github.com/erxes/erxes/issues/3725)
> feat(store): fix service duplications

- packages/ui-forms/src/settings/properties/components/GenerateField.tsx
> Deals add product group property

- packages/plugin-engages-api/src/graphql/resolvers/Query.ts
- packages/plugin-engages-api/src/graphql/schema/engage.ts
- packages/plugin-logs-ui/src/emailDelivery/components/EmailDelivery.tsx
- packages/plugin-logs-ui/src/emailDelivery/components/Row.tsx
- packages/plugin-logs-ui/src/emailDelivery/containers/EmailDelivery.tsx
- packages/plugin-logs-ui/src/emailDelivery/queries.ts
[Issue 3731](https://github.com/erxes/erxes/issues/3731)
> show & add email filter to email deliveries

- packages/plugin-contacts-api/src/utils.ts
- packages/plugin-engages-api/src/sender.ts
[Issue 3736](https://github.com/erxes/erxes/issues/3736)
> close #3736

- packages/plugin-cards-api/src/graphql/resolvers/mutations/deals.ts
- packages/plugin-cards-api/src/graphql/resolvers/mutations/utils.ts
- packages/plugin-cards-api/src/graphql/resolvers/queries/deals.ts
- packages/plugin-inbox-api/src/graphql/resolvers/conversationMutations.ts
- packages/plugin-inbox-api/src/graphql/resolvers/integrationMutations.ts
- packages/plugin-knowledgebase-api/src/graphql/resolvers/knowledgeBaseMutations.ts
- packages/plugin-tags-api/src/graphql/resolvers/queries/tags.ts
Fix typescript errors in plugins.
> fix typescript errors and remove unused imports

- packages/plugin-cards-api/src/graphql/resolvers/queries/boards.ts
- packages/plugin-cards-api/src/graphql/resolvers/queries/utils.ts
- packages/plugin-cards-api/src/graphql/schema/deal.ts
- packages/plugin-cards-api/src/graphql/schema/growthHack.ts
- packages/plugin-cards-api/src/graphql/schema/task.ts
- packages/plugin-cards-api/src/graphql/schema/ticket.ts
> added new parameter in cards plugin

- packages/plugin-cards-api/src/graphql/schema/task.ts
- packages/plugin-cards-api/src/graphql/schema/ticket.ts
- packages/plugin-cards-api/src/models/utils.ts
- packages/ui-cards/src/boards/components/portable/AddForm.tsx
> Convert multiple conversation to single card

- packages/plugin-contacts-api/src/models/Customers.ts
[Issue 3776](https://github.com/erxes/erxes/issues/3776)
> close #3776

- packages/workers/src/data/utils.ts
- packages/workers/src/worker/import/bulkInsert.worker.ts
- packages/workers/src/worker/import/utils.ts
- packages/workers/src/worker/workerUtil.ts
A worker throws an error when importing a large amount of data.
> Fix worker bug

- README.md
[ISSUE](https://github.com/erxes/erxes/issues/3614)
Deleted the links which led to 404 errors
> [FIX]: fixed links for documentation in README

- packages/plugin-products-ui/src/components/product/ProductList.tsx
> Add temprorary segment to product

- docs/docs/code-reference/api/common-functions.md
- docs/docs/deployment/deployment/docker-compose.md
- docs/docs/developer/developing-integration-plugins.md
- docs/docs/developer/developing-plugins.md
- docs/sidebars.js
**Plugin docs improvoment for developers**
1. Create plugin command improvement:
2. Create integration plugin command development:
3. Create plugin documentation improvement:
Screenshots 📸 :
**Code reference improvement:**
**Create integration plugin doc improvement:**
**Create general plugin doc improvement:**
> Development docs improvement

- packages/plugin-clientportal-api/src/graphql/resolvers/mutations/clientPortalUser.ts
- packages/plugin-clientportal-api/src/graphql/schema/clientPortal.ts
- packages/plugin-clientportal-api/src/graphql/schema/clientPortalUser.ts
- packages/plugin-clientportal-api/src/models/ClientPortalUser.ts
- packages/plugin-clientportal-api/src/models/definitions/clientPortal.ts
- packages/plugin-clientportal-ui/src/components/forms/Config.tsx
- packages/plugin-clientportal-ui/src/graphql/queries.ts
- packages/plugin-clientportal-ui/src/types.ts
- widgets/client/form/containers/AppContext.tsx
improved client portal OTP login method
> Improve client portal

- packages/erxes-ui/src/team/graphql/queries.ts
> fix team member property logic

- packages/plugin-inbox-ui/src/inbox/containers/conversationDetail/workarea/ConvertTo.tsx
- packages/ui-cards/src/boards/containers/portable/AddForm.tsx
[ISSUE](https://github.com/erxes/erxes/issues/3970)
Bug fixed that can't create cards in conversation.
> Fix inbox add card

- packages/plugin-cards-api/src/graphql/resolvers/customResolvers/deal.ts
- packages/plugin-cards-api/src/graphql/resolvers/customResolvers/growthHack.ts
- packages/plugin-cards-api/src/graphql/resolvers/customResolvers/task.ts
- packages/plugin-cards-api/src/graphql/resolvers/customResolvers/ticket.ts
- packages/plugin-cards-api/src/graphql/resolvers/mutations/utils.ts
[ISSUE](https://github.com/erxes/erxes/issues/3973)
**Fix the bug that assigned users, customers, and companies are fetching with an error when a card subscription is working.**
> Fix bug that subscription data fetching in cards

- client-portal/modules/main/components/Header.tsx
- client-portal/modules/styles/main.ts
- packages/plugin-cards-api/src/messageBroker.ts
[ISSUE](https://github.com/erxes/erxes/issues/3998)
**Add a logout button on the client portal and fix a task stage order.**
Screenshot
> Cp order improvement

- packages/plugin-emailtemplates-api/src/graphql/resolvers/queries/emailTemplates.ts
- packages/plugin-emailtemplates-api/src/graphql/schema/emailTemplate.ts
- packages/plugin-emailtemplates-ui/src/containers/List.tsx
- packages/plugin-emailtemplates-ui/src/graphql/queries.ts
- packages/plugin-inbox-ui/src/inbox/components/InboxCore.tsx
- packages/ui-inbox/src/settings/integrations/components/mail/emailTemplate/EmailTemplate.tsx
- packages/ui-inbox/src/settings/integrations/containers/mail/MailForm.tsx
- packages/ui-inbox/src/settings/integrations/graphql/queries.ts
[ISSUE](https://github.com/erxes/erxes/issues/3994)
**Email templates search not working on inbox**.
> Fix emailtemplates search

- packages/plugin-clientportal-api/src/constants.ts
- packages/plugin-clientportal-api/src/forms.ts
- packages/plugin-clientportal-api/src/graphql/schema/clientPortalUser.ts
- packages/plugin-clientportal-api/src/models/definitions/clientPortalUser.ts
- packages/plugin-clientportal-ui/src/components/detail/ClientPortalUserDetails.tsx
- packages/plugin-clientportal-ui/src/components/detail/InfoSection.tsx
- packages/plugin-clientportal-ui/src/components/detail/LeftSidebar.tsx
- packages/plugin-clientportal-ui/src/components/forms/ClientPortalUserForm.tsx
- packages/plugin-clientportal-ui/src/containers/CustomFieldsSection.tsx
- packages/plugin-clientportal-ui/src/graphql/mutations.ts
- packages/plugin-clientportal-ui/src/graphql/queries.ts
- packages/plugin-clientportal-ui/src/types.ts
added client portal users  in custom properties and added avatar field
> add custom property and avatar on clientportalusers

- packages/erxes-ui/src/team/components/detail/LeftSidebar.tsx
Team detail хуудсан дээрх Properties ийг багцлаад Modal болгосон
> Modal implemented on Properties

- packages/plugin-contacts-api/src/messageBroker.ts
Adding **companies.find** consumeRPCQueue
> Contacts plugin improvement

- client-portal/modules/styles/tickets.ts
- client-portal/modules/ticket/components/Detail.tsx
- client-portal/modules/ticket/components/Ticket.tsx
- client-portal/modules/ticket/containers/Detail.tsx
- client-portal/modules/ticket/containers/Form.tsx
- client-portal/modules/ticket/containers/Ticket.tsx
- client-portal/modules/ticket/graphql/index.ts
- client-portal/modules/ticket/graphql/mutations.ts
- client-portal/modules/ticket/graphql/queries.ts
- client-portal/pages/tickets/TicketHeader.tsx
- packages/plugin-clientportal-api/src/connectionResolver.ts
- packages/plugin-clientportal-api/src/graphql/resolvers/comment.ts
- packages/plugin-clientportal-api/src/graphql/resolvers/index.ts
- packages/plugin-clientportal-api/src/graphql/resolvers/mutations/comment.ts
- packages/plugin-clientportal-api/src/graphql/resolvers/mutations/index.ts
- packages/plugin-clientportal-api/src/graphql/resolvers/queries/clientPortal.ts
- packages/plugin-clientportal-api/src/graphql/resolvers/queries/comment.ts
- packages/plugin-clientportal-api/src/graphql/resolvers/queries/index.ts
- packages/plugin-clientportal-api/src/graphql/schema/clientPortal.ts
- packages/plugin-clientportal-api/src/graphql/schema/comment.ts
- packages/plugin-clientportal-api/src/graphql/typeDefs.ts
- packages/plugin-clientportal-api/src/models/Comment.ts
- packages/plugin-clientportal-api/src/models/definitions/comment.ts
- packages/plugin-clientportal-ui/src/components/comments/CardDetailAction.tsx
- packages/plugin-clientportal-ui/src/components/comments/styles.ts
- packages/plugin-clientportal-ui/src/configs.js
- packages/plugin-clientportal-ui/src/containers/comments/CardDetailAction.tsx
- packages/plugin-clientportal-ui/src/graphql/mutations.ts
- packages/plugin-clientportal-ui/src/graphql/queries.ts
- packages/ui-cards/src/boards/graphql/mutations.ts
**Description**
This PR adds the comment section on a ticket feature and removes unnecessary codes.
**Type of PR**
This PR is an `enhancement`.
**Checklists:**
**Notes:**
1. Need to update the card plugin's UI, client portal plugin's UI, API, and client portal to enter these updates.
**Screenshots:** 📸 📸 📸
> Comment section on client portal and ticket

- packages/plugin-cards-api/src/graphql/resolvers/queries/utils.ts
- packages/plugin-cards-api/src/graphql/schema/common.ts
- packages/plugin-cards-api/src/graphql/schema/deal.ts
- packages/plugin-cards-api/src/graphql/schema/task.ts
- packages/plugin-cards-api/src/graphql/schema/ticket.ts
- packages/plugin-cards-api/src/models/definitions/boards.ts
- packages/ui-cards/src/boards/components/RightMenu.tsx
- packages/ui-cards/src/boards/components/editForm/Sidebar.tsx
- packages/ui-cards/src/boards/containers/MainActionBar.tsx
- packages/ui-cards/src/boards/containers/Stage.tsx
- packages/ui-cards/src/boards/graphql/mutations.ts
- packages/ui-cards/src/boards/types.ts
- packages/ui-cards/src/deals/graphql/queries.ts
- packages/ui-cards/src/tasks/graphql/queries.ts
- packages/ui-cards/src/tickets/graphql/queries.ts
> update(cards):filter by departments and branches

- packages/plugin-contacts-api/src/messageBroker.ts
- packages/plugin-facebook-api/src/graphql/schema.ts
- packages/plugin-facebook-api/src/handleFacebookMessage.ts
- packages/plugin-facebook-api/src/models/ConversationMessages.ts
- packages/plugin-facebook-api/src/models/definitions/conversationMessages.ts
- packages/plugin-facebook-ui/src/configs.js
- packages/plugin-facebook-ui/src/types.ts
- packages/plugin-inbox-api/src/graphql/resolvers/conversationMutations.ts
Facebook-messenger internalnote is fixed.
> Facebook-messenger internalnote fixed

- client-portal/modules/knowledgeBase/containers/ArticleList.tsx
- client-portal/modules/knowledgeBase/containers/CategoryList.tsx
- client-portal/modules/knowledgeBase/graphql/queries.ts
- client-portal/pages/knowledge-base/article/index.tsx
- client-portal/pages/knowledge-base/category/index.tsx
- packages/plugin-clientportal-api/src/graphql/resolvers/queries/clientPortal.ts
- packages/plugin-clientportal-api/src/graphql/schema/clientPortal.ts
- packages/plugin-contacts-api/src/messageBroker.ts
Clientportal search within choosed knowledgebase fixed.
> Clientportal search fix.

- packages/plugin-clientportal-api/src/graphql/resolvers/mutations/clientPortalUser.ts
- packages/plugin-clientportal-api/src/graphql/schema/clientPortal.ts
- packages/plugin-clientportal-api/src/graphql/schema/clientPortalUser.ts
- packages/plugin-clientportal-api/src/models/ClientPortalUser.ts
- packages/plugin-clientportal-api/src/models/definitions/clientPortal.ts
- packages/plugin-clientportal-api/src/models/definitions/clientPortalUser.ts
- packages/plugin-clientportal-ui/src/components/Form.tsx
- packages/plugin-clientportal-ui/src/components/detail/LeftSidebar.tsx
- packages/plugin-clientportal-ui/src/components/detail/VerificationForm.tsx
- packages/plugin-clientportal-ui/src/components/forms/Config.tsx
- packages/plugin-clientportal-ui/src/components/list/ClientPortalUserList.tsx
- packages/plugin-clientportal-ui/src/components/list/ClientPortalUserRow.tsx
- packages/plugin-clientportal-ui/src/constants.ts
- packages/plugin-clientportal-ui/src/containers/details/VerificationForm.tsx
- packages/plugin-clientportal-ui/src/graphql/mutations.ts
- packages/plugin-clientportal-ui/src/graphql/queries.ts
- packages/plugin-clientportal-ui/src/types.ts
> client portal user manual verification

- packages/plugin-products-api/src/dataloaders/resolvers/queries/products.ts
- packages/plugin-products-api/src/graphql/schema/product.ts
- packages/plugin-products-api/src/models/definitions/products.ts
- packages/ui-products/src/components/CategoryForm.tsx
- packages/ui-products/src/graphql/mutations.ts
- packages/ui-products/src/graphql/queries.ts
- packages/ui-products/src/types.ts
- meta field nemeh
- meta field ni too baiwal tuhain toonoos baga buyu tentsuu categoruudiig butsaana. string baiwal ijil utgataig bustaana
> Product improvment

- packages/plugin-webbuilder-ui/src/components/entries/styles.tsx
- packages/plugin-webbuilder-ui/src/containers/entries/List.tsx
Add scroll on contentType and get last 60 contentType
> webbuilder perPage add

- packages/core/src/data/resolvers/mutations/users.ts
- packages/core/src/data/schema/brand.ts
- packages/core/src/db/models/Brands.ts
- packages/core/src/db/models/definitions/brands.ts
- packages/erxes-ui/src/team/components/UserForm.tsx
- packages/erxes-ui/src/team/containers/UserForm.tsx
- packages/erxes-ui/src/team/graphql/queries.ts
Team Member's selected brands doesn't saved issue has fixed.
> Team Member's Brands chooser fix

- packages/erxes-ui/src/team/containers/UserForm.tsx
Team member's brand chooser query loading added.
> Brands query loading added

- packages/erxes-ui/src/team/containers/UserForm.tsx
- packages/plugin-facebook-api/src/models/definitions/conversationMessages.ts
- packages/plugin-facebook-api/src/receiveMessage.ts
- packages/plugin-inbox-api/src/receiveMessage.ts
Facebook-messenger's conversation date doesn't update issue has fixed.
> Facebook-messenger's conversation date fix

- packages/erxes-ui/src/components/map/Map.tsx
- packages/plugin-clientportal-api/src/afterMutations.ts
- packages/plugin-clientportal-api/src/graphql/resolvers/mutations/clientPortal.ts
- packages/plugin-clientportal-api/src/graphql/schema/clientPortal.ts
- packages/plugin-clientportal-api/src/models/definitions/clientPortal.ts
- packages/plugin-clientportal-ui/src/components/forms/General.tsx
- packages/plugin-clientportal-ui/src/graphql/mutations.ts
- packages/plugin-clientportal-ui/src/graphql/queries.ts
- packages/plugin-clientportal-ui/src/types.ts
- packages/ui-cards/src/boards/components/editForm/ChildrenSection.tsx
cp add deal notification and deal children map property fix
> cp add deal notification and deal children map property fix

- widgets/client/form/components/Form.tsx
> fix(widgets):redirect back to page when form has validation error

- client-portal/modules/styles/tickets.ts
- client-portal/modules/ticket/components/Ticket.tsx
- client-portal/modules/ticket/graphql/queries.ts
- packages/plugin-clientportal-api/src/graphql/resolvers/mutations/clientPortal.ts
> update(clientportal):add stage changed date column in tickets list

- packages/plugin-inbox-api/src/graphql/resolvers/conversationMutations.ts
> fix(inbox):update conversation content when send messege

- packages/core/src/data/resolvers/mutations/users.ts
> fix(core):can't save channels when invite team members

- packages/plugin-cards-api/src/graphql/resolvers/queries/utils.ts
- packages/plugin-cards-api/src/graphql/schema/deal.ts
- packages/plugin-cards-api/src/graphql/schema/task.ts
- packages/plugin-cards-api/src/graphql/schema/ticket.ts
- packages/ui-cards/src/boards/components/portable/AddForm.tsx
- packages/ui-cards/src/boards/components/portable/GenerateAddFormFields.tsx
> fix(cards):can't save required fields with logic when field hidden

- packages/api-plugin-template.erxes/src/index.ts
- packages/erxes-ui/src/components/Chooser.tsx
- packages/erxes-ui/src/types.ts
- packages/plugin-cards-api/src/forms.ts
- packages/plugin-cards-ui/src/SelectCard.tsx
- packages/plugin-cards-ui/src/configs.js
- packages/plugin-contacts-api/src/forms.ts
- packages/plugin-contacts-ui/src/configs.js
- packages/plugin-contacts-ui/src/relation/SelectContacts.tsx
- packages/plugin-contacts-ui/src/relation/queries.ts
- packages/plugin-forms-api/src/graphql/resolvers/field.ts
- packages/plugin-forms-api/src/graphql/resolvers/queries/fields.ts
- packages/plugin-forms-api/src/graphql/schema/field.ts
- packages/plugin-forms-api/src/models/Fields.ts
- packages/plugin-forms-api/src/models/definitions/fields.ts
- packages/plugin-forms-ui/src/components/PropertyRow.tsx
- packages/plugin-forms-ui/src/components/RelationForm.tsx
- packages/plugin-forms-ui/src/configs.js
- packages/plugin-forms-ui/src/containers/RelationForm.tsx
- packages/plugin-forms-ui/src/queries.ts
- packages/ui-cards/src/boards/components/portable/AddForm.tsx
- packages/ui-cards/src/boards/containers/portable/AddForm.tsx
- packages/ui-cards/src/boards/graphql/queries.ts
- packages/ui-cards/src/boards/types.ts
- packages/ui-contacts/src/companies/components/CompanyForm.tsx
- packages/ui-contacts/src/companies/containers/CompanyForm.tsx
- packages/ui-contacts/src/customers/components/CustomerForm.tsx
- packages/ui-contacts/src/customers/containers/CustomerForm.tsx
- packages/ui-forms/src/settings/properties/graphql/queries.ts
> Properties relation

- packages/plugin-contacts-ui/src/customers/components/list/CustomersList.tsx
- packages/plugin-contacts-ui/src/customers/components/list/LeadFilter.tsx
- packages/plugin-contacts-ui/src/customers/components/list/Sidebar.tsx
- packages/plugin-contacts-ui/src/customers/containers/filters/LeadFilter.tsx
- packages/ui-contacts/src/customers/styles.ts
Search filter forms on contacts (Customer/Leads)
> search bar on filter by forms(contacts)

- client-portal/modules/ticket/components/Group.tsx
- client-portal/modules/ticket/components/Ticket.tsx
- client-portal/modules/ticket/components/TicketHeader.tsx
- client-portal/modules/ticket/containers/Group.tsx
- client-portal/modules/ticket/containers/Ticket.tsx
- client-portal/modules/ticket/graphql/queries.ts
- packages/plugin-clientportal-api/src/graphql/resolvers/queries/clientPortal.ts
- packages/plugin-clientportal-api/src/graphql/schema/clientPortal.ts
- packages/plugin-clientportal-api/src/utils.ts
> clientportal team3

- client-portal/modules/common/utils.ts
Task:Бүх дотоодын client portal-уудын хувьд лого & falcon зурагнуудыг харагддаг болгож өгнө үү
Team2: 2point 
Team Leader: Soyombo
by:Munkhjargal FE
> client-portal logo svg fix

- packages/plugin-contacts-api/src/models/Companies.ts
- packages/plugin-contacts-api/src/utils.ts
- packages/plugin-inbox-api/src/graphql/resolvers/widgetMutations.ts
> Company search

- packages/plugin-cards-api/src/models/utils.ts
> conversation conversion log

- packages/ui-segments/src/components/SidebarFilter.tsx
- packages/ui-segments/src/containers/Filter.tsx
Segments add drop down if segment has parent
> Segments dropdown

- packages/plugin-cards-api/src/constants.ts
- packages/plugin-cards-api/src/exporter.ts
- packages/plugin-logs-api/src/messageBroker.ts
> Export improve

- packages/core/src/dashboardSchemas/Users.js
- packages/plugin-cards-api/src/dashboardSchemas/DealsAssigneduser.js
- packages/plugin-cards-api/src/dashboardSchemas/TasksAssigneduser.js
- packages/plugin-cards-api/src/dashboardSchemas/TicketsAssigneduser.js
- packages/plugin-inbox-api/src/dashboardSchemas/Conversations.js
> Dashboard improve

- packages/erxes-ui/src/components/DateFilter.tsx
- packages/ui-cards/src/boards/components/portable/AddForm.tsx
- packages/ui-cards/src/boards/containers/BoardSelect.tsx
> Inbox improve

- packages/ui-cards/src/tickets/components/TicketItem.tsx
> Perf add startdate complete

- client-portal/pages/index.tsx
- packages/plugin-clientportal-api/src/constants.ts
- packages/plugin-clientportal-api/src/graphql/resolvers/mutations/clientPortalUser.ts
- packages/plugin-clientportal-api/src/graphql/schema/clientPortalUser.ts
- packages/plugin-clientportal-api/src/middlewares/cpUserMiddleware.ts
- packages/plugin-clientportal-api/src/models/ClientPortalUser.ts
- packages/plugin-clientportal-api/src/models/utils.ts
> update(clientportal): Socialpay miniapp login from clientportal

- .github/workflows/semgrep.yml
semgrep ci
[ISSUE](https://github.com/erxes/erxes/issues/4571)
> semgrep ci

- .github/workflows/cypress.yaml
- cli/configs.json.cli.sample
- client-portal/modules/common/Button.cy.tsx
- cypress.config.js
- cypress/fixtures/example.json
- cypress/support/commands.js
- cypress/support/component-index.html
- cypress/support/component.js
- cypress/support/e2e.js
- cypress/tests/api/demo.cy.js
- cypress/tests/ui/auth.cy.js
- cypress/tests/ui/contacts/company.cy.js
- cypress/tests/ui/contacts/customer.cy.js
- cypress/tests/ui/contacts/lead.cy.js
- docker/docker-compose.yaml
- package.json
- setup-tests.js
- vite.config.ts
[ISSUE](https://github.com/erxes/erxes/issues/4568)
Test automation
> Cypress configuration

- packages/plugin-loyalties-api/src/automations.ts
- packages/plugin-loyalties-api/src/messageBroker.ts
- packages/plugin-loyalties-api/src/models/ScoreLogs.ts
- packages/plugin-loyalties-api/src/models/definitions/scoreLog.ts
- packages/plugin-loyalties-ui/src/automations/automation.tsx
- packages/plugin-loyalties-ui/src/automations/components/ScoreForm.tsx
> update(loyalties):score action on automations

- .gitignore
- cypress.config.js
- cypress/database/seedLocalMongoDB.js
- cypress/database/tags.json
- cypress/database/users.json
- cypress/support/commands.js
- cypress/tests/api/demo.cy.js
- cypress/tests/ui/auth.cy.js
- cypress/tests/ui/contacts/company.cy.js
- cypress/tests/ui/contacts/customer.cy.js
- cypress/tests/ui/contacts/lead.cy.js
- package.json
> cypress seedDB

- .github/workflows/cypress.yaml
- cypress.config.js
> cypress ci node version change

- packages/plugin-facebook-api/src/helpers.ts
- packages/plugin-inbox-api/src/graphql/subscriptionPlugin.js
> update(facebook): fix subscriptions

- .github/workflows/cypress.yaml
- packages/gateway/package.json
- packages/gateway/src/commands/watch-template.ts
> cypress fix

- .github/workflows/plugin-timeclock-api.yaml
- .github/workflows/plugin-timeclock-ui.yaml
- packages/plugin-timeclock-api/src/graphql/resolvers/schedule.ts
- packages/plugin-timeclock-api/src/graphql/resolvers/utils.ts
Show corresponding detail to selected day - mobile App
> Timeclock report by user

- packages/erxes-ui/src/components/step/styles.ts
- packages/plugin-inbox-ui/src/forms/components/List.tsx
- packages/plugin-inbox-ui/src/forms/components/Row.tsx
- packages/plugin-inbox-ui/src/settings/integrations/containers/messenger/AddOns.tsx
- fix skip callout ui bug
- add flow type to form list
- show all form when create messenger
> fix(integration): messenger form select

- packages/erxes-ui/src/styles/global-styles.ts
- packages/ui-inbox/src/settings/integrations/styles.ts
- fix search bar of email template chooser in email widget
- fix popover arrow
> fix(emailWidget): search bar of email template chooser

- cypress/tests/ui/auth.cy.js
- cypress/tests/ui/contacts/company.cy.js
- cypress/tests/ui/contacts/customer.cy.js
- cypress/tests/ui/contacts/lead.cy.js
> added timeout in cypress 

- .github/workflows/semgrep.yml
> semgrep ci changed

- packages/erxes-ui/src/components/pagination/Pagination.tsx
- packages/erxes-ui/src/components/pagination/PerPageChooser.tsx
> Fix perpage number

- cypress/tests/contacts/ui/company.cy.js
- cypress/tests/contacts/ui/lead.cy.js
> skip data needed TC

- packages/plugin-clientportal-api/src/graphql/resolvers/queries/clientPortal.ts
- packages/plugin-clientportal-api/src/graphql/schema/clientPortal.ts
- packages/plugin-clientportal-api/src/utils.ts
- packages/plugin-clientportal-ui/src/components/detail/RightSidebar.tsx
- packages/plugin-clientportal-ui/src/containers/CardItems.tsx
- packages/plugin-clientportal-ui/src/graphql/queries.ts
> update(clientportal): show related cards of clientportal user 

- packages/plugin-payment-api/src/controllers.ts
- packages/plugin-payment-api/src/views/index.pug
> Added payment-name to the payments list

- packages/plugin-loans-api/src/graphql/schema/contractType.ts
- packages/plugin-loans-api/src/models/definitions/contractTypes.ts
- packages/plugin-loans-ui/src/classificationHistory/styles.ts
- packages/plugin-loans-ui/src/contractTypes/components/ContractTypeForm.tsx
- packages/plugin-loans-ui/src/contractTypes/graphql/mutations.ts
- packages/plugin-loans-ui/src/contractTypes/graphql/queries.ts
- packages/plugin-loans-ui/src/contractTypes/styles.ts
- packages/plugin-loans-ui/src/contracts/components/list/ContractForm.tsx
- packages/plugin-loans-ui/src/contracts/components/list/ContractRow.tsx
- packages/plugin-loans-ui/src/contracts/components/list/ContractsList.tsx
- packages/plugin-loans-ui/src/contracts/graphql/queries.ts
- packages/plugin-loans-ui/src/contracts/styles.ts
- packages/plugin-loans-ui/src/contracts/types.ts
- packages/plugin-loans-ui/src/periodLocks/styles.ts
- packages/plugin-savings-api/src/graphql/resolvers/mutations/contracts.ts
- packages/plugin-savings-api/src/graphql/schema/contract.ts
- packages/plugin-savings-api/src/models/contracts.ts
- packages/plugin-savings-ui/src/contractTypes/styles.ts
- packages/plugin-savings-ui/src/contracts/components/detail/ExpandForm.tsx
- packages/plugin-savings-ui/src/contracts/components/list/ContractForm.tsx
- packages/plugin-savings-ui/src/contracts/components/list/ContractRow.tsx
- packages/plugin-savings-ui/src/contracts/components/list/ContractsList.tsx
- packages/plugin-savings-ui/src/contracts/components/schedules/SchedulesList.tsx
- packages/plugin-savings-ui/src/contracts/graphql/mutations.ts
- packages/plugin-savings-ui/src/contracts/graphql/queries.ts
- packages/plugin-savings-ui/src/contracts/styles.ts
- packages/plugin-savings-ui/src/periodLocks/styles.ts
- packages/ui-tags/src/containers/Tagger.tsx
Contract type productType
UI changes table and form
Expand contract change contract Type
> loans and savings update

- packages/plugin-pos-api/src/messageBroker.ts
- packages/plugin-posclient-api/src/graphql/resolvers/mutations/configs.ts
- packages/plugin-posclient-api/src/graphql/resolvers/mutations/payments.ts
- packages/plugin-posclient-api/src/graphql/resolvers/mutations/posUsers.ts
- packages/plugin-posclient-api/src/graphql/resolvers/queries/report.ts
- packages/plugin-posclient-api/src/routes.ts
- packages/plugin-posclient-api/src/subscriptions/schema.ts
- packages/plugin-syncerkhet-api/src/graphql/resolvers/mutations/checkSynced.ts
> Federation new

- packages/plugin-clientportal-api/src/graphql/resolvers/mutations/clientPortal.ts
- packages/plugin-clientportal-api/src/messageBroker.ts
- packages/plugin-clientportal-api/src/models/utils.ts
> update(clientportal): refactor createCard method

- packages/plugin-clientportal-api/src/graphql/resolvers/mutations/clientPortal.ts
- packages/plugin-clientportal-api/src/messageBroker.ts
- packages/plugin-clientportal-api/src/models/utils.ts
> update(clientportal): refactor create card

- pos/modules/products/components/productItem/productItem.market.tsx
- pos/modules/products/components/search/search.market.tsx
- pos/store/ui.store.ts
> fix search focus bug

- packages/plugin-loyalties-ui/src/configs/assignmentCampaign/components/CreateForm.tsx
- packages/plugin-loyalties-ui/src/configs/assignmentCampaign/components/EditForm.tsx
> hotfix(loyalties):can't select segmentIds in assignment form

- packages/plugin-loans-api/src/models/definitions/transactions.ts
- packages/plugin-loans-api/src/models/invoices.ts
- packages/plugin-loans-api/src/models/transactions.ts
- packages/plugin-loans-api/src/models/utils/scheduleUtils.ts
- packages/plugin-loans-api/src/models/utils/transactionUtils.ts
- packages/plugin-loans-ui/src/contracts/components/invoices/InvoiceRow.tsx
> Loan credit bug fix

- packages/api-utils/src/automations.ts
- packages/plugin-loyalties-api/src/graphql/resolvers/queries/assignments.ts
- packages/plugin-loyalties-api/src/graphql/schema/assignmentCampaign.ts
- packages/plugin-loyalties-api/src/models/AssignmentCampaigns.ts
- packages/plugin-loyalties-api/src/models/definitions/assignmentCampaigns.ts
- packages/plugin-loyalties-ui/src/configs/assignmentCampaign/common/SegmentFields.tsx
- packages/plugin-loyalties-ui/src/configs/assignmentCampaign/components/EditForm.tsx
- packages/plugin-loyalties-ui/src/configs/assignmentCampaign/graphql/mutations.ts
- packages/plugin-loyalties-ui/src/configs/assignmentCampaign/graphql/queries.ts
- packages/plugin-loyalties-ui/src/configs/assignmentCampaign/types.ts
- packages/plugin-pos-api/src/automations.ts
- packages/plugin-pos-api/src/forms.ts
- packages/plugin-riskassessment-api/src/models/RiskAssessment.ts
- packages/plugin-riskassessment-api/src/utils.ts
- packages/plugin-segments-api/src/messageBroker.ts
> feat(loyalties):add ability award assignment based on counter customField value of segment

- packages/plugin-products-api/src/essyncer.js
> fix(products):unitPrice type of essyncer

- packages/plugin-pos-api/src/essyncer.js
- packages/plugin-products-api/src/essyncer.js
> hotfix(pos): can't count correctly because of items:<nested> from essyncer

- packages/plugin-pos-api/src/essyncer.js
> Revert "hotfix(pos): can't count correctly because of items:<nested> from essyncer"

- packages/plugin-payment-api/src/graphql/resolvers/mutations/invoices.ts
- packages/plugin-payment-api/src/graphql/schema/invoices.ts
- packages/plugin-payment-api/src/permissions.js
> Custom create invoice

- packages/plugin-clientportal-api/src/graphql/resolvers/mutations/clientPortalUser.ts
- packages/plugin-clientportal-api/src/graphql/schema/clientPortalUser.ts
- packages/plugin-clientportal-api/src/messageBroker.ts
- packages/plugin-clientportal-api/src/models/ClientPortalUser.ts
- packages/plugin-clientportal-api/src/models/definitions/clientPortalUser.ts
> update(clientportal): add secondary password to users

- packages/plugin-clientportal-api/src/graphql/resolvers/mutations/clientPortal.ts
- packages/plugin-clientportal-api/src/graphql/resolvers/mutations/clientPortalUser.ts
- packages/plugin-clientportal-api/src/graphql/schema/clientPortal.ts
- packages/plugin-clientportal-api/src/models/ClientPortalUser.ts
- packages/plugin-clientportal-api/src/models/definitions/clientPortal.ts
- packages/plugin-clientportal-api/src/models/definitions/clientPortalUser.ts
- packages/plugin-clientportal-ui/src/components/forms/Config.tsx
- packages/plugin-clientportal-ui/src/graphql/queries.ts
- packages/plugin-clientportal-ui/src/types.ts
> Cp improve

- packages/plugin-clientportal-api/package.json
- packages/plugin-clientportal-api/src/constants.ts
- packages/plugin-clientportal-api/src/graphql/resolvers/mutations/clientPortalUser.ts
- packages/plugin-clientportal-api/src/models/utils.ts
- packages/plugin-clientportal-api/src/socialpayUtils.ts
> Socialpay3.0

- packages/plugin-contacts-api/src/configs.ts
- packages/plugin-inbox-api/src/constants.ts
- packages/plugin-inbox-api/src/graphql/integrationTypeDefs.ts
- packages/plugin-inbox-api/src/graphql/resolvers/widgetMutations.ts
- packages/plugin-inbox-api/src/models/definitions/integrations.ts
- packages/plugin-inbox-ui/src/bookings/components/Booking.tsx
- packages/plugin-inbox-ui/src/forms/components/Lead.tsx
- packages/ui-leads/src/components/step/SuccessStep.tsx
- packages/ui-leads/src/types.ts
> update(forms): verify customers email via form submission

- packages/plugin-chats-api/src/graphql/resolvers/queries/chats.ts
- packages/plugin-chats-api/src/graphql/schema/chat.ts
> Exm feed improve

- packages/core-ui/public/locales/mn.json
- packages/plugin-loans-api/src/graphql/resolvers/collateral.ts
- packages/plugin-loans-api/src/graphql/resolvers/contract.ts
- packages/plugin-loans-api/src/graphql/resolvers/insuranceType.ts
- packages/plugin-loans-api/src/graphql/resolvers/invoice.ts
- packages/plugin-loans-api/src/graphql/resolvers/periodLock.ts
- packages/plugin-loans-api/src/graphql/resolvers/transaction.ts
- packages/plugin-loans-ui/src/contracts/components/common/ContractSection.tsx
- packages/plugin-loans-ui/src/contracts/components/detail/RightSidebar.tsx
- packages/plugin-loans-ui/src/contracts/types.ts
- packages/plugin-loans-ui/src/locales/mn.json
- packages/plugin-savings-api/src/graphql/resolvers/contract.ts
- packages/plugin-savings-api/src/graphql/resolvers/transaction.ts
- packages/plugin-savings-api/src/graphql/schema/contract.ts
- packages/plugin-savings-api/src/messageBroker.ts
- packages/plugin-savings-ui/src/contracts/components/common/DetailInfo.tsx
- packages/plugin-savings-ui/src/contracts/components/detail/CloseForm.tsx
- packages/plugin-savings-ui/src/contracts/components/detail/ExpandForm.tsx
- packages/plugin-savings-ui/src/contracts/components/detail/InterestChangeForm.tsx
- packages/plugin-savings-ui/src/contracts/components/detail/LoanContractSection.tsx
- packages/plugin-savings-ui/src/contracts/components/detail/RightSidebar.tsx
- packages/plugin-savings-ui/src/contracts/components/list/StoreInterestForm.tsx
- packages/plugin-savings-ui/src/contracts/components/schedules/ScheduleRow.tsx
- packages/plugin-savings-ui/src/contracts/graphql/queries.ts
- packages/plugin-savings-ui/src/contracts/types.ts
- packages/plugin-savings-ui/src/locales/mn.json
- packages/plugin-savings-ui/src/periodLocks/components/PeriodLockForm.tsx
- packages/plugin-savings-ui/src/transactions/components/TransactionForm.tsx
> Saving loan validation

- packages/plugin-inbox-api/src/graphql/integrationTypeDefs.ts
- packages/plugin-inbox-api/src/models/Integrations.ts
- packages/plugin-inbox-api/src/models/definitions/integrations.ts
- packages/ui-inbox/src/settings/integrations/graphql/queries.ts
> Add createdAt in Integration

- packages/plugin-knowledgebase-api/src/graphql/resolvers/knowledgeBaseCategory.ts
> check publish and draft in Knowledgebase

- packages/plugin-goals-api/src/constants.ts
- packages/plugin-goals-api/src/models/Goals.ts
- packages/plugin-goals-ui/src/components/goalForm.tsx
- packages/plugin-goals-ui/src/components/goalView.tsx
> [Goal plugin] Test result Issues

- packages/plugin-cards-api/src/reports.ts
- packages/plugin-multierkhet-api/src/graphql/resolvers/queries/configs.ts
> Cards reports 

- packages/plugin-exm-ui/src/components/Appearance.tsx
> exm core web arreapance color fix

- packages/plugin-payment-api/src/graphql/resolvers/mutations/invoices.ts
> fix invoice permission

- packages/plugin-clientportal-api/src/utils.ts
> Added transporter.sendMulticast to ClientPortalSendNotification

- packages/plugin-instagram-api/src/middlewares/loginMiddleware.ts
- packages/plugin-instagram-ui/src/components/conversationDetail/workarea/TagMessage.tsx
- packages/plugin-instagram-ui/src/components/conversationDetail/workarea/TaggedMessageModal.tsx
- packages/plugin-instagram-ui/src/components/conversationDetail/workarea/styles.ts
- packages/plugin-instagram-ui/src/configs.js
- packages/plugin-instagram-ui/src/containers/TagMessageContainer.tsx
- packages/ui-inbox/src/settings/integrations/components/store/Entry.tsx
> inbox Something went wrong. () fix

- packages/plugin-inbox-ui/src/inbox/components/conversationDetail/workarea/RespondBox.tsx
- packages/plugin-inbox-ui/src/inbox/containers/conversationDetail/RespondBox.tsx
- packages/ui-inbox/src/inbox/graphql/queries.ts
> response template possible search from content

- packages/plugin-viber-api/src/viber/messageListen.ts
> Viber fix conversation

- packages/ui-inbox/src/settings/integrations/components/common/IntegrationListItem.tsx
> repair-button

- packages/core-ui/src/modules/settings/importExport/import/components/Form.tsx
- packages/core-ui/src/modules/settings/importExport/import/components/TypeForm.tsx
- packages/core-ui/src/modules/settings/importExport/import/components/list/Histories.tsx
- packages/core-ui/src/modules/settings/importExport/import/containers/TypeForm.tsx
- packages/plugin-inbox-api/src/configs.ts
- packages/plugin-inbox-api/src/constants.ts
- packages/plugin-inbox-api/src/exporter.ts
- packages/plugin-inbox-api/src/messageBroker.ts
> import export conversation add

- packages/plugin-clientportal-api/src/graphql/resolvers/queries/clientPortal.ts
> knowledgebase artice status draft

- packages/plugin-clientportal-api/src/graphql/resolvers/mutations/clientPortalUser.ts
- packages/plugin-clientportal-api/src/graphql/schema/clientPortalUser.ts
- packages/plugin-clientportal-api/src/middlewares/cpUserMiddleware.ts
- packages/plugin-clientportal-api/src/models/definitions/clientPortal.ts
- packages/plugin-clientportal-ui/src/components/forms/Config.tsx
- packages/plugin-clientportal-ui/src/types.ts
> Added ClientPortalLoginWithEmailOtp

- packages/plugin-instagram-api/src/commonUtils.ts
- packages/plugin-instagram-api/src/middlewares/loginMiddleware.ts
> config instagram

- packages/plugin-inbox-ui/src/inbox/containers/Tagger.tsx
- packages/ui-inbox/src/settings/integrations/components/common/IntegrationListItem.tsx
> QA [1.5.11] [IMAP] IMAP fetch andQA [1.5.9] [tags] inbox

- packages/plugin-inbox-ui/src/inbox/components/conversationDetail/workarea/RespondBox.tsx
- packages/plugin-inbox-ui/src/inbox/components/conversationDetail/workarea/responseTemplate/PopoverContent.tsx
- packages/plugin-inbox-ui/src/inbox/containers/conversationDetail/RespondBox.tsx
- packages/plugin-inbox-ui/src/inbox/containers/conversationDetail/responseTemplate/PopoverContent.tsx
- packages/ui-inbox/src/inbox/graphql/queries.ts
> QA [1.5.9] = [inbox, response] search

- packages/plugin-msdynamic-api/src/graphql/resolvers/mutations/checkDynamic.ts
> price check improve

- packages/core-ui/src/modules/settings/team/components/UserInvitationForm.tsx
- packages/plugin-contacts-api/src/imports.ts
> impports and user invitation branch update

- packages/core-ui/src/modules/settings/profile/components/EditProfileForm.tsx
- packages/core-ui/src/modules/settings/profile/containers/Profile.tsx
- packages/core/src/data/resolvers/mutations/users.ts
- packages/core/src/data/schema/user.ts
- packages/erxes-ui/src/team/graphql/mutations.ts
> Profile improve

- packages/plugin-facebook-api/src/store.ts
> getOrCreateComment

- packages/plugin-cards-api/src/reports.ts
- packages/plugin-reports-ui/src/graphql/queries.ts
> reports -filters ticket , task, deal= [User,date,branch,department,board,pipeline,Labels,stage,stageType,tag,custom properties]

- packages/plugin-calls-api/src/messageBroker.ts
- packages/plugin-facebook-api/src/messageBroker.ts
- packages/plugin-inbox-api/src/graphql/integrationTypeDefs.ts
- packages/plugin-inbox-api/src/graphql/resolvers/integration.ts
- packages/plugin-instagram-api/src/messageBroker.ts
- packages/plugin-integrations-api/src/messageBroker.ts
- packages/plugin-zalo-api/src/server/brokers/conversationMessages.ts
- packages/ui-inbox/src/settings/integrations/graphql/queries.ts
> Remove unused resolver from inbox

- packages/plugin-cards-api/src/reports.ts
> report probability-filter

- packages/plugin-automations-api/src/utils.ts
- packages/plugin-facebook-api/src/automations/index.ts
- packages/plugin-facebook-api/src/automations/messages.ts
- packages/plugin-facebook-api/src/models/Bots.ts
- packages/plugin-facebook-ui/src/automations/bots/components/Form.tsx
- packages/plugin-facebook-ui/src/automations/bots/containers/List.tsx
- packages/plugin-facebook-ui/src/automations/components/action/ReplyFbMessage.tsx
- packages/plugin-facebook-ui/src/automations/components/trigger/CommentForm.tsx
- packages/ui-automations/src/components/forms/actions/placeHolder/Attribution.tsx
> hotfix(automation):won't wait 10 second for check target is in segment

- packages/plugin-facebook-api/src/store.ts
> Facebook comment get or create comment fix

- packages/plugin-facebook-api/src/controller.ts
- packages/plugin-facebook-api/src/store.ts
> replyConversation

- packages/plugin-facebook-api/src/controller.ts
- packages/plugin-facebook-api/src/store.ts
> Post receive fix2

- packages/plugin-engages-ui/src/campaigns/components/MessageListRow.tsx
> Fix issue with the engage tag

- packages/ui-inbox/src/settings/integrations/components/facebook/RefreshPermission.tsx
> chore : Repair button integration

- packages/plugin-loans-api/src/messageBroker.ts
- packages/plugin-syncpolaris-api/src/utils/loan/getLoanSchedule.ts
- packages/plugin-syncpolaris-api/src/utils/toSyncUtils/utils.ts
> sync polaris loan 's schedule

- packages/plugin-facebook-api/src/graphql/resolvers/queries.ts
> facebook-messenger query

- packages/plugin-clientportal-api/src/graphql/resolvers/clientPortalUser.ts
- packages/plugin-clientportal-api/src/graphql/resolvers/index.ts
- packages/plugin-clientportal-api/src/graphql/resolvers/mutations/clientPortal.ts
- packages/plugin-clientportal-api/src/graphql/resolvers/queries/clientPortal.ts
- packages/plugin-clientportal-api/src/graphql/schema/clientPortal.ts
- packages/plugin-clientportal-api/src/models/utils.ts
- packages/plugin-clientportal-ui/src/components/cardRightSidebarSection/Detail.tsx
- packages/plugin-clientportal-ui/src/components/cardRightSidebarSection/VendorSection.tsx
- packages/plugin-clientportal-ui/src/components/forms/ClientPortalParticipantForm.tsx
- packages/plugin-clientportal-ui/src/constants.ts
- packages/plugin-clientportal-ui/src/containers/ClientPortalParticipantForm.tsx
- packages/plugin-clientportal-ui/src/containers/ClientUserChooser.tsx
- packages/plugin-clientportal-ui/src/containers/cardsRightSidebarSection/ClientSection.tsx
- packages/plugin-clientportal-ui/src/containers/cardsRightSidebarSection/VendorSection.tsx
- packages/plugin-clientportal-ui/src/graphql/mutations.ts
- packages/plugin-clientportal-ui/src/graphql/queries.ts
- packages/plugin-clientportal-ui/src/styles.tsx
- packages/plugin-clientportal-ui/src/types.ts
> vendor user in cards

- packages/ui-inbox/src/inbox/components/conversationDetail/workarea/mail/MailHeader.tsx
> IMAP email  no-reply 

- packages/plugin-calls-api/src/graphql/resolvers/queries.ts
- packages/plugin-calls-ui/src/components/IncomingCall.tsx
- packages/plugin-calls-ui/src/components/SipProvider/index.tsx
- packages/plugin-calls-ui/src/containers/SipProvider.tsx
- packages/plugin-inbox-api/src/graphql/conversationTypeDefs.ts
> debug on call

- packages/plugin-instagram-api/src/controller.ts
- packages/plugin-instagram-api/src/middlewares/loginMiddleware.ts
- packages/plugin-instagram-ui/src/containers/Authorization.tsx
- packages/plugin-instagram-ui/src/routes.tsx
> fix login instagram

- packages/ui-contacts/src/customers/constants.ts
> Merge Customers Fields

- packages/ui-inbox/src/settings/integrations/components/mail/MailChooser.tsx
- packages/ui-inbox/src/settings/integrations/components/mail/MailForm.tsx
- packages/ui-inbox/src/settings/integrations/containers/mail/MailForm.tsx
- packages/ui-inbox/src/settings/integrations/graphql/queries.ts
> imap query

- packages/plugin-facebook-ui/src/containers/Authorization.tsx
- packages/ui-contacts/src/customers/constants.ts
> login facebook

- packages/plugin-facebook-api/src/middlewares/loginMiddleware.ts
- packages/plugin-facebook-ui/src/containers/Authorization.tsx
- packages/ui-contacts/src/customers/constants.ts
> Facebook login fix

- packages/plugin-facebook-ui/src/containers/Authorization.tsx
- packages/plugin-instagram-ui/src/containers/Authorization.tsx
> instagram reload

- packages/plugin-cards-api/src/reports.ts
- packages/plugin-clientportal-api/src/messageBroker.ts
- packages/plugin-contacts-api/package.json
- packages/plugin-contacts-api/src/configs.ts
- packages/plugin-contacts-api/src/messageBroker.ts
- packages/plugin-contacts-api/src/reports/constants.ts
- packages/plugin-contacts-api/src/reports/reports.ts
- packages/plugin-contacts-api/src/reports/template/chart.ts
- packages/plugin-contacts-api/src/reports/template/report.ts
- packages/plugin-contacts-api/src/reports/utils.ts
- packages/plugin-forms-api/src/graphql/resolvers/queries/fields.ts
- packages/plugin-forms-api/src/graphql/schema/field.ts
- packages/plugin-forms-api/src/utils.ts
- packages/plugin-insight-ui/src/components/chart/ChartFormField.tsx
- packages/plugin-insight-ui/src/components/chart/TableRenderer.tsx
- packages/plugin-insight-ui/src/components/utils/SelectClientPortal.tsx
- packages/plugin-insight-ui/src/components/utils/SelectLeads.tsx
- packages/plugin-insight-ui/src/containers/chart/ChartFormField.tsx
- packages/plugin-insight-ui/src/containers/chart/ChartRenderer.tsx
- packages/plugin-insight-ui/src/graphql/queries.ts
- packages/plugin-insight-ui/src/types.ts
- packages/plugin-insight-ui/src/utils.ts
- packages/plugin-tags-api/src/graphql/resolvers/queries/tags.ts
- packages/plugin-tags-api/src/utils.ts
> chore: contact chart for insight

- create-erxes-app/bin/create-erxes-app.js
> Update default plugins

- packages/plugin-clientportal-api/src/middlewares/cpUserMiddleware.ts
> broadcast bug

- packages/plugin-loans-api/src/connectionResolver.ts
- packages/plugin-loans-api/src/graphql/resolvers/index.ts
- packages/plugin-loans-api/src/graphql/resolvers/mutations/index.ts
- packages/plugin-loans-api/src/graphql/resolvers/mutations/nonBalanceTransactions.ts
- packages/plugin-loans-api/src/graphql/resolvers/nonBalanceTransaction.ts
- packages/plugin-loans-api/src/graphql/resolvers/queries/index.ts
- packages/plugin-loans-api/src/graphql/resolvers/queries/nonBalanceTransactions.ts
- packages/plugin-loans-api/src/graphql/schema/loan.ts
- packages/plugin-loans-api/src/graphql/schema/nonBalanceTransaction.ts
- packages/plugin-loans-api/src/models/definitions/nonBalanceTransactions.ts
- packages/plugin-loans-api/src/models/nonBalanceTransactions.ts
- packages/plugin-loans-api/src/permissions.js
- packages/plugin-loans-ui/src/configs.js
- packages/plugin-loans-ui/src/constants.ts
- packages/plugin-loans-ui/src/nonBalanceTransaction/components/AddForm.tsx
- packages/plugin-loans-ui/src/nonBalanceTransaction/components/DetailForm.tsx
- packages/plugin-loans-ui/src/nonBalanceTransaction/components/List.tsx
- packages/plugin-loans-ui/src/nonBalanceTransaction/components/NonBalanceTransactionRow.tsx
- packages/plugin-loans-ui/src/nonBalanceTransaction/containers/Form.tsx
- packages/plugin-loans-ui/src/nonBalanceTransaction/containers/List.tsx
- packages/plugin-loans-ui/src/nonBalanceTransaction/containers/NonBalanceTransactionList.tsx
- packages/plugin-loans-ui/src/nonBalanceTransaction/graphql/index.ts
- packages/plugin-loans-ui/src/nonBalanceTransaction/graphql/mutations.ts
- packages/plugin-loans-ui/src/nonBalanceTransaction/graphql/queries.ts
- packages/plugin-loans-ui/src/nonBalanceTransaction/types.ts
- packages/plugin-loans-ui/src/routes.tsx
- packages/plugin-loans-ui/src/transactions/components/TransactionRow.tsx
- packages/plugin-syncpolaris-ui/src/settings/components/GeneralSettings.tsx
> non balance transaction && polaris fix

- packages/plugin-imap-api/src/graphql/resolvers/queries.ts
> imap-false

- packages/erxes-ui/src/types.ts
- packages/plugin-forms-api/src/graphql/schema/field.ts
- packages/plugin-forms-api/src/models/Forms.ts
- packages/plugin-forms-api/src/models/definitions/fields.ts
- packages/ui-forms/src/forms/components/FieldForm.tsx
- packages/ui-forms/src/forms/graphql/mutations.ts
- packages/ui-forms/src/forms/graphql/queries.ts
- packages/ui-forms/src/settings/properties/components/GenerateField.tsx
- packages/ui-forms/src/settings/properties/components/PropertyForm.tsx
- packages/ui-forms/src/settings/properties/graphql/mutations.ts
- packages/ui-forms/src/settings/properties/graphql/queries.ts
- packages/ui-forms/src/settings/properties/types.ts
> add regex to form fields and customer properties

- packages/plugin-savings-api/src/graphql/resolvers/mutations/transactions.ts
- packages/plugin-savings-api/src/graphql/schema/transaction.ts
> fix: clear code

- .commitlintrc.json
- .husky/commit-msg
- package.json
- yarn.lock
> Commitlint hooks

- packages/plugin-clientportal-api/src/auth/authUtils.ts
- packages/plugin-clientportal-api/src/graphql/resolvers/mutations/clientPortalUser.ts
- packages/plugin-clientportal-api/src/graphql/schema/clientPortal.ts
- packages/plugin-clientportal-api/src/graphql/schema/clientPortalUser.ts
- packages/plugin-clientportal-api/src/middlewares/cpUserMiddleware.ts
- packages/plugin-clientportal-api/src/models/definitions/clientPortal.ts
- packages/plugin-clientportal-ui/src/components/Form.tsx
- packages/plugin-clientportal-ui/src/components/forms/Config.tsx
- packages/plugin-clientportal-ui/src/graphql/queries.ts
- packages/plugin-clientportal-ui/src/types.ts
> 2FA clientportal

- packages/plugin-dailyco-api/src/graphql/resolvers/mutations.ts
> Dailyco video call

- packages/plugin-facebook-api/src/handleFacebookMessage.ts
- packages/plugin-facebook-api/src/messageBroker.ts
- packages/plugin-inbox-api/src/graphql/resolvers/conversationMutations.ts
- packages/plugin-instagram-api/src/handleInstagramMessage.ts
- packages/plugin-instagram-api/src/messageBroker.ts
- packages/plugin-instagram-ui/src/containers/Authorization.tsx
> [inbox] [bug] inbox:sendNotifications

- packages/plugin-loans-api/src/models/utils/transactionUtils.ts
- packages/plugin-savings-api/src/graphql/resolvers/mutations/contracts.ts
- packages/plugin-savings-api/src/graphql/schema/contract.ts
> feat: client saving contract request

- packages/erxes-ui/src/components/richTextEditor/RichTextEditor.context.ts
- packages/erxes-ui/src/components/richTextEditor/RichTextEditorContent/RichTextEditorContent.tsx
- packages/erxes-ui/src/components/richTextEditor/TEditor.tsx
- packages/erxes-ui/src/components/richTextEditor/hooks/useExtensions.ts
- packages/erxes-ui/src/components/richTextEditor/nodes/Mention.tsx
- packages/erxes-ui/src/components/richTextEditor/utils/getMentionSuggestions.tsx
- packages/erxes-ui/src/components/richTextEditor/utils/replaceMentionNode.ts
- packages/erxes-ui/src/containers/RichTextEditor.tsx
- packages/plugin-documents-ui/src/components/Form.tsx
- packages/plugin-inbox-ui/src/inbox/components/conversationDetail/workarea/Editor.tsx
- packages/plugin-inbox-ui/src/inbox/containers/conversationDetail/RespondBox.tsx
- Resolved inbox editors flushSync error
- Removed static document editor's name 
> fix: inbox RTE mention plugin & document editor issue

- packages/plugin-savings-api/src/graphql/resolvers/mutations/contracts.ts
> fix: github committed bug

- packages/ui-cards/src/boards/styles/item.ts
> Fix cards description

- packages/plugin-calls-api/src/connectionResolver.ts
- packages/plugin-calls-api/src/graphql/resolvers/mutations.ts
- packages/plugin-calls-api/src/graphql/resolvers/queries.ts
- packages/plugin-calls-api/src/graphql/typeDefs.ts
- packages/plugin-calls-api/src/models/Operators.ts
- packages/plugin-calls-api/src/models/definitions/integrations.ts
- packages/plugin-calls-api/src/models/definitions/operators.ts
- packages/plugin-calls-ui/src/components/Keypad.tsx
- packages/plugin-calls-ui/src/containers/KeyPad.tsx
- packages/plugin-calls-ui/src/graphql/mutations.ts
- packages/plugin-calls-ui/src/graphql/queries.ts
> feat(calls): added pause feature

- packages/plugin-facebook-ui/src/components/Form.tsx
> Unnecessary use of conditional expression for default assignment.

- packages/plugin-facebook-ui/src/components/Form.tsx
- packages/ui-inbox/src/settings/integrations/components/facebook/RefreshPermission.tsx
> Facebook UI refresh permission

- packages/ui-inbox/src/settings/integrations/components/facebook/RefreshPermission.tsx
> A fragment with only one child is redundant.

- packages/ui-inbox/src/settings/integrations/components/facebook/RefreshPermission.tsx
> instagram A fragment with only one child is redundant.

- packages/ui-inbox/src/inbox/components/conversationDetail/workarea/facebook/UserName.tsx
> 'userId' PropType is defined but prop is never used

- packages/ui-inbox/src/inbox/components/conversationDetail/workarea/facebook/styles.ts
> Remove this unused import of 'typography'.

- packages/plugin-facebook-api/src/models/definitions/comment_conversations_reply.ts
- packages/plugin-facebook-api/src/models/definitions/postConversations.ts
>  Facebook api  definitions

- packages/plugin-facebook-api/src/messageBroker.ts
- packages/plugin-facebook-api/src/models/Configs.ts
- packages/plugin-facebook-api/src/receiveMessage.ts
> Prefer using nullish coalescing operator (`??`) instead of a logical or (`||`), as it is a safer operator.

- packages/plugin-facebook-api/src/handleFacebookMessage.ts
> facebook messages

- packages/plugin-facebook-api/src/utils.ts
> Facebook api utils fix2

- packages/plugin-facebook-api/src/commonUtils.ts
- packages/plugin-facebook-api/src/receiveComment.ts
> CommonUtils

- packages/plugin-automations-api/src/graphql/resolvers/mutations/automations.ts
- packages/plugin-automations-api/src/graphql/resolvers/queries/automations.ts
- packages/plugin-automations-api/src/models/Automations.ts
- packages/plugin-automations-api/src/models/Notes.ts
- packages/plugin-automations-api/src/utils.ts
- packages/plugin-cards-api/src/automations.ts
- packages/plugin-cards-api/src/connectionResolver.ts
- packages/plugin-cards-api/src/documents.ts
- packages/plugin-cards-api/src/logUtils.ts
- packages/plugin-cards-api/src/segments.ts
- packages/plugin-cards-api/src/utils.ts
- packages/plugin-facebook-ui/src/automations/index.tsx
- packages/plugin-webhooks-ui/src/automations/automations.tsx
> Hackathon tuguldur

- packages/ui-cards/src/boards/components/portable/AddForm.tsx
> fix cards convert save button

- packages/erxes-ui/src/layout/styles.ts
> fix dropdown segments

- packages/plugin-loans-api/src/graphql/resolvers/mutations/contracts.ts
- packages/plugin-loans-api/src/graphql/resolvers/mutations/transactions.ts
- packages/plugin-loans-api/src/graphql/resolvers/queries/classification.ts
- packages/plugin-loans-api/src/graphql/resolvers/queries/contractTypes.ts
- packages/plugin-loans-api/src/graphql/resolvers/queries/contracts.ts
- packages/plugin-loans-api/src/graphql/resolvers/queries/insuranceTypes.ts
- packages/plugin-loans-api/src/graphql/resolvers/queries/invoices.ts
- packages/plugin-loans-api/src/graphql/resolvers/queries/nonBalanceTransactions.ts
- packages/plugin-loans-api/src/graphql/resolvers/queries/periodLocks.ts
- packages/plugin-loans-api/src/graphql/resolvers/queries/transactions.ts
- packages/plugin-savings-api/src/graphql/resolvers/mutations/contracts.ts
- packages/plugin-savings-api/src/graphql/resolvers/mutations/transactions.ts
- packages/plugin-savings-api/src/graphql/resolvers/queries/contractTypes.ts
- packages/plugin-savings-api/src/graphql/resolvers/queries/contracts.ts
- packages/plugin-savings-api/src/graphql/resolvers/queries/periodLocks.ts
query bug fix
client mutation validation fix
> fix: Front and back bug fix 

- packages/plugin-loans-api/src/graphql/resolvers/queries/transactions.ts
- packages/plugin-loans-api/src/models/classification.ts
- packages/plugin-loans-api/src/models/contractTypes.ts
- packages/plugin-loans-api/src/models/contracts.ts
- packages/plugin-loans-api/src/models/general.ts
- packages/plugin-loans-api/src/models/insuranceTypes.ts
- packages/plugin-loans-api/src/models/interestCorrection.ts
- packages/plugin-loans-api/src/models/invoices.ts
- packages/plugin-loans-api/src/models/periodLock.ts
- packages/plugin-loans-api/src/models/schedules.ts
- packages/plugin-loans-api/src/models/storedInterest.ts
- packages/plugin-loans-ui/src/contractTypes/components/ContractTypeDetailInfo.tsx
- packages/plugin-loans-ui/src/contractTypes/components/ContractTypeForm.tsx
- packages/plugin-loans-ui/src/contractTypes/components/ContractTypeRow.tsx
- packages/plugin-loans-ui/src/contracts/components/list/ClassificationForm.tsx
- packages/plugin-loans-ui/src/contracts/components/list/ContractForm.tsx
- packages/plugin-loans-ui/src/contracts/components/list/ContractsList.tsx
- packages/plugin-loans-ui/src/contracts/types.ts
- packages/plugin-loans-ui/src/contracts/utils/customGraphic.ts
- packages/plugin-loans-ui/src/transactions/components/ChangeTrForm.tsx
- packages/plugin-loans-ui/src/transactions/components/TransactionForm.tsx
- packages/plugin-loans-ui/src/transactions/components/TransactionRow.tsx
- packages/plugin-savings-api/src/graphql/resolvers/mutations/contracts.ts
- packages/plugin-savings-api/src/graphql/resolvers/queries/contracts.ts
- packages/plugin-savings-api/src/graphql/resolvers/queries/transactions.ts
- packages/plugin-savings-api/src/graphql/schema/contract.ts
- packages/plugin-savings-api/src/graphql/schema/transaction.ts
transaction check balance
add filter\
> Contract type fix

- packages/plugin-loans-api/src/graphql/resolvers/queries/contracts.ts
- packages/plugin-loans-api/src/graphql/schema/contract.ts
- packages/plugin-savings-api/src/models/utils/closeUtils.ts
> fix: contract filter

- packages/plugin-loans-api/src/graphql/resolvers/queries/contracts.ts
> update pageSize to perPage

- packages/plugin-loans-api/src/graphql/resolvers/queries/transactions.ts
- packages/plugin-loans-api/src/graphql/schema/transaction.ts
- packages/plugin-savings-api/src/graphql/resolvers/queries/transactions.ts
loan and saving transaction fix filter
> Loantransactionfilter

- packages/plugin-calls-ui/src/components/Keypad.tsx
- packages/plugin-calls-ui/src/containers/IncomingCall.tsx
- packages/plugin-calls-ui/src/containers/SipProvider.tsx
> chore(calls): check undefined value

- packages/ui-cards/src/boards/components/editForm/Left.tsx
> fix description height edit 

- packages/plugin-burenscoring-api/src/graphql/resolvers/queries/queries.ts
- packages/plugin-burenscoring-ui/src/config/components/Settings.tsx
> field name changed  in burenscoring query

- packages/workers/src/data/resolvers/queries/importHistory.ts
> fix import history data

- packages/plugin-burenscoring-api/src/graphql/resolvers/mutations/toSaveBurenScoring.ts
- packages/plugin-burenscoring-api/src/messageBroker.ts
- packages/plugin-loans-api/src/graphql/resolvers/contract.ts
- packages/plugin-loans-api/src/graphql/resolvers/mutations/contracts.ts
- packages/plugin-loans-api/src/graphql/resolvers/queries/transactions.ts
- packages/plugin-loans-api/src/graphql/schema/contract.ts
- packages/plugin-loans-api/src/messageBroker.ts
- packages/plugin-loans-api/src/models/contracts.ts
- packages/plugin-loans-ui/src/routes.tsx
- packages/plugin-loans-ui/src/settings/components/CreditLoanSettings.tsx
- packages/plugin-loans-ui/src/settings/components/CreditScore.tsx
- packages/plugin-loans-ui/src/settings/components/Sidebar.tsx
- packages/plugin-loans-ui/src/settings/containers/Settings.tsx
- packages/plugin-savings-api/src/models/transactions.ts
- packages/plugin-savings-api/src/models/utils/transactionUtils.ts
- yarn.lock
loans and saving transaction bug
> fix: transaction

- packages/plugin-timeclock-api/src/graphql/resolvers/queries.ts
- packages/plugin-timeclock-ui/src/components/sidebar/SideBar.tsx
> fix set params

- packages/plugin-assets-api/src/common/constant/asset.ts
- packages/plugin-assets-api/src/common/types/asset.ts
- packages/plugin-assets-api/src/connectionResolver.ts
- packages/plugin-assets-api/src/dataloaders/index.ts
- packages/plugin-assets-api/src/dataloaders/kbArticle.ts
- packages/plugin-assets-api/src/dataloaders/kbCategory.ts
- packages/plugin-assets-api/src/dataloaders/resolvers/customResolvers/asset.ts
- packages/plugin-assets-api/src/dataloaders/resolvers/customResolvers/assetCategory.ts
- packages/plugin-assets-api/src/dataloaders/resolvers/customResolvers/index.ts
- packages/plugin-assets-api/src/dataloaders/resolvers/customResolvers/itemSourceLocation.ts
- packages/plugin-assets-api/src/dataloaders/resolvers/customResolvers/kbArticlesHistory.ts
- packages/plugin-assets-api/src/dataloaders/resolvers/customResolvers/movement.ts
- packages/plugin-assets-api/src/dataloaders/resolvers/customResolvers/movementItems.ts
- packages/plugin-assets-api/src/dataloaders/resolvers/index.ts
- packages/plugin-assets-api/src/dataloaders/resolvers/mutations/asset.ts
- packages/plugin-assets-api/src/dataloaders/resolvers/queries/index.ts
- packages/plugin-assets-api/src/dataloaders/resolvers/queries/kbArticlesHistories.ts
- packages/plugin-assets-api/src/graphql/schema/assets.ts
- packages/plugin-assets-api/src/models/KBArticleHistories.ts
- packages/plugin-assets-api/src/models/definitions/assets.ts
- packages/plugin-assets-ui/src/asset/components/actions/Assign/Topic.tsx
- packages/plugin-assets-ui/src/asset/components/detail/BasicInfo.tsx
- packages/plugin-assets-ui/src/asset/components/detail/KbArticleHistories.tsx
- packages/plugin-assets-ui/src/asset/containers/detail/BasicInfo.tsx
- packages/plugin-assets-ui/src/asset/containers/detail/KbArticleHistories.tsx
- packages/plugin-assets-ui/src/asset/graphql/queries.ts
- packages/plugin-assets-ui/src/common/types.ts
> feat(assets): added ability set history when kb articles changed

- packages/plugin-khanbank-api/src/graphql/schema/accounts.ts
- packages/plugin-khanbank-api/src/khanbank/api/accounts.ts
> Khanbank bug

- packages/plugin-automations-ui/src/components/forms/actions/styles.ts
- packages/plugin-automations-ui/src/components/forms/actions/subForms/SendMail.tsx
- packages/plugin-cards-api/src/automations.ts
- packages/plugin-notifications-api/src/automations.ts
- packages/plugin-notifications-ui/src/automations/components/sendNotifcation.tsx
- packages/ui-automations/src/components/forms/actions/ItemRow.tsx
- packages/ui-automations/src/styles.ts
> Improvement automations
