erxes/erxes

- src/modules/customers/containers/CustomerAssociate.tsx
- src/modules/knowledgeBase/components/knowledge/KnowledgeRow.tsx
- tslint.json
Hello,
These changes should resolve #614.
With `no-string-literal` disabled, I only encountered two lint errors.
> Resolve no-string-literal TSLint errors

- tslint.json
This should fix #615
Enabling/Removing this rule entirely from the `tslint.json` file _did not_ result in any violations. Looks like it wasn't necessary.
```shell
yarn run tslint 'src/**/*.ts'
```
I went ahead and removed it.
> Fix disabled tslint no-shadowed-variable

- src/modules/layout/containers/Navigation.tsx
This query has no parameters which can change to override cache
but its backing data changes all the time as new conversations are
created by clients so the default settings mean that a logged in user who
is browsing another filter (eg: Resolved conversations) will not see that
new conversations are pending until they return to the default view.
> disable caching on `unreadConversationsCountQuery`

- src/modules/inbox/components/assignBox/AssignBox.tsx
- src/modules/inbox/components/assignBox/AssignBoxPopover.tsx
- src/modules/inbox/components/leftSidebar/Sidebar.tsx
- src/modules/inbox/components/leftSidebar/StatusFilterPopover.tsx
- src/modules/inbox/containers/Inbox.tsx
- src/modules/inbox/containers/Resolver.tsx
- src/modules/inbox/containers/Tagger.tsx
- src/modules/inbox/containers/leftSidebar/ConversationList.tsx
- src/modules/inbox/containers/leftSidebar/FilterList.tsx
- src/modules/inbox/containers/leftSidebar/StatusFilterPopover.tsx
- src/modules/inbox/containers/leftSidebar/index.ts
The additional sidebar, status popover, and any other components in the Inbox that show summary data like total conversation count are not up to date with management actions like resolving a conversation or tagging a conversation taken by the logged in user.
This adds a context that any interested component in the Inbox tree can use to either notify other components across the tree that a management action has been performed locally, or to receive such a notification and re-fetch its own data accordingly.
> Keep sidebar & popover counts synced with management actions in Team Inbox

- src/modules/layout/components/QuickNavigation.tsx
- src/modules/notifications/components/Widget.tsx
- src/modules/notifications/containers/NotificationsLatest.tsx
- src/modules/notifications/containers/Widget.tsx
- src/modules/notifications/context.tsx
- src/routes.tsx
Both the widget and popover components use their own query, and now their own subscriptions to track notifications. The subscription from the popover is stopped when the popover is not rendered so a new notification could come in (eg: an assignment or @mention on a conversation) which would increment the count in the quick navigation widget but not update the popover content. The new notification would appear to be missing and cannot be dismissed without entering the full screen notification view and checking for unreads.
This adds a provider so both components can share a single set of notification count & content queries and subscriptions for additional new notifications. This also prevents duplicate "notificationInserted" subscriptions from the same client.
You can see here an internal …
> Fix notification widget and notification popover being out of sync.

- ui/src/modules/settings/importHistory/components/Histories.tsx
- ui/src/modules/settings/importHistory/components/Sidebar.tsx
- ui/src/modules/settings/properties/constants.ts
ImportHistory sidebar menu was imported from modules/settings/properties/components/Sidebar, which was faulty. A separate sidebar for each module will be fitting.
> add sidebar menu to importHistory

- .github/PULL_REQUEST_TEMPLATE.md
To make it easier for the reviewers, I am adding a pull request template file so that the future PRs would have a description skeleton by default.
I see we already have issue templates under https://github.com/erxes/erxes/tree/master/.github and it's an attempt to accomplish the same thing for PRs.
Note: I'm not so familiar with the review process in this repo, we could add code owners to the repository so that they'd be notified every time a new PR is put up.
> feat(add): Create PULL_REQUEST_TEMPLATE.md

- ui/src/modules/settings/general/components/GeneralSettings.tsx
[ISSUE](https://github.com/erxes/erxes/issues/#1809)
Add missing Google Cloud Storage Bucket field in system config for a  file upload
> add: google cloud storage bucket name in system config

- ui/src/modules/boards/containers/MainActionBar.tsx
[Issue #1824](https://github.com/erxes/erxes/issues/#1824)
Do not show clear filter button shows when the deal card modal show up
> fix: show clear filter button only for search filters

- ui/src/locales/de.json
- ui/src/locales/en.json
- ui/src/locales/es.json
- ui/src/locales/fr.json
- ui/src/locales/hi.json
- ui/src/locales/it.json
- ui/src/locales/ja.json
- ui/src/locales/ko.json
- ui/src/locales/mn.json
- ui/src/locales/pt-br.json
- ui/src/locales/ru.json
- ui/src/locales/vi.json
- ui/src/locales/yi.json
- ui/src/locales/zh-cn.json
- ui/src/modules/common/components/ConfirmDialog.tsx
- ui/src/modules/common/components/filter/Filter.tsx
- ui/src/modules/engage/components/MessengerForm.tsx
- ui/src/modules/knowledgeBase/components/article/ArticleForm.tsx
- ui/src/modules/layout/components/AuthLayout.tsx
- ui/src/modules/settings/brands/components/BrandRow.tsx
- ui/src/modules/settings/brands/components/Brands.tsx
- ui/src/modules/settings/brands/components/Sidebar.tsx
- ui/src/modules/settings/channels/components/Channels.tsx
- ui/src/modules/settings/integrations/components/InstallCode.tsx
- ui/src/modules/settings/team/components/UserConfirmation.tsx
This PR addresses:
- Some spots in the UI where localization exists but is not used (eg: buttons like Cancel and Delete are hard-coded in English).
- A few missing keys are added (eg: "Add new brand" button), but only with English and German languages.
- The filter chip component is updated so that flags in the query params are also localized (eg: "unassigned=true" will now localize the string "unassigned" instead of ignoring it's value "true", and a localization for "unassigned" already exists in the locale files).
> Minor updates to localization.

- ui/src/modules/common/components/editor/Editor.tsx
- ui/src/modules/inbox/components/conversationDetail/workarea/Editor.tsx
HI, II implemented an option to hide the response templates
Old behavior:
Typing a short message like "Hi", if there is a response template that matches, the response template will shows up and when I press the enter key to send my "Hi" message, the response template replaces my original message, this is annoying, I need to use the mouse to send the message.
New behavior:
The same as before, but now if you want to send your message and not the response template, you can press the escape key to hide the response templates and then the enter key to send the "Hi" message
Thanks
> Implemented escape to dismiss response templates

- ui/src/modules/activityLogs/components/items/boardItems/Task.tsx
[ISSUE](https://github.com/erxes/erxes/issues/2155)
Can't assign a team member to a task from the Contact profile
> Contact detail task assignee

- ui/src/modules/common/components/form/Form.tsx
[ISSUE](https://github.com/erxes/erxes/issues/2134)
The product price value validator was int. Now it has changed to float.
> Product price value validator fix

- ui/src/modules/settings/importHistory/containers/HistoryDetail.tsx
- ui/src/modules/settings/importHistory/containers/ImportIndicator.tsx
- ui/src/modules/settings/importHistory/types.ts
Made Redis, RabbitMQ optional
Reason:
Requiring big dependencies for simple usages becoming the installation process slow and hard.
Solution:
If there is a REDIS_HOST env variable available then Redis will be used otherwise just runtime variable will be used.
If there is a RABBITMQ_HOST env variable available then RabbitMQ will be used for message broker otherwise just TCP connections will be used.
> Replace redis

- ui/src/modules/settings/integrations/components/common/IntegrationList.tsx
- ui/src/modules/settings/integrations/components/common/IntegrationListItem.tsx
- ui/src/modules/settings/integrations/graphql/queries.ts
When creating integrations, the third-party service configurations like API token, webhook url etc are only filled in create forms. After the integration is created, such data above is not visible in the list. With this PR, callpro, chatfuel, smooch, whatsapp & telnyx configurations will show up in the list.
> show external integration data in appstore list

- CONTRIBUTING.md
Hey folks 👋 
The relative links to issue (one is `issues` and another is `issue`) doesn't point to the issues page of `erxes/erxes`.
Rather, I have now added absolute links for it to redirect to proper page.
The first link points to [Issues](https://github.com/erxes/erxes/issues) page
And the second link points to the [New Issue](https://github.com/erxes/erxes/issues/new/choose) page
I hope that is expected behavior :)
> fix: incorrect issues page links in CONTRIBUTING.md

- api/src/__tests__/dashboardQueries.test.ts
- api/src/__tests__/engageMessageDb.test.ts
- api/src/__tests__/engageMessageQueries.test.ts
- api/src/data/resolvers/engage.ts
- api/src/data/resolvers/mutations/engages.ts
- api/src/data/schema/engage.ts
- api/src/db/factories.ts
- api/src/db/models/definitions/engages.ts
- ui/src/modules/engage/components/MessageList.tsx
- ui/src/modules/engage/components/MessageListRow.tsx
- ui/src/modules/engage/graphql/queries.ts
- ui/src/modules/engage/types.ts
- Save created user id in engages.
- Show created user's username or email in engage list
- Improve test & coverage.
> save created user id in engages

- ui/src/modules/engage/components/AutoAndManualForm.tsx
- ui/src/modules/engage/components/EngageStats.tsx
- ui/src/modules/engage/components/FormBase.tsx
- ui/src/modules/engage/components/MessageList.tsx
- ui/src/modules/engage/components/Sidebar.tsx
- ui/src/modules/engage/components/VisitorForm.tsx
- ui/src/modules/engage/containers/MessageListRow.tsx
- ui/src/modules/engage/containers/withFormMutations.tsx
- ui/src/modules/engage/routes.tsx
- ui/src/modules/layout/components/Navigation.tsx
- ui/src/modules/settings/general/components/EngageConfigs.tsx
- ui/src/modules/settings/general/components/Sidebar.tsx
- ui/src/modules/settings/general/routes.tsx
"Engage message" seemed confusing to some customers. Therefore, with this PR, the UI part of engage message is gonna be renamed to "campaign"s.
> rename engage to campaign

- engages-email-sender/src/sender.ts
Email campaign title can now be customized with custom fields like .
Consider a campaign with the following title. "Hello {{ customer.firstName }}".
Then the email will be delivered with a title "Hello John", considering a customer with a name John exists.
> replace field name attributes of campaign title

- ui/src/modules/engage/components/MessageListRow.tsx
- ui/src/modules/engage/graphql/queries.ts
Campaign list item used stats, smsStats resolvers which made additional connection to engages-email-sender just to show status, total target count in the UI. The status & target count could be determined without having to connect to sub service, which is done in this PR.
> stop using stats, smsStats resolver in list query

- api/src/apolloClient.ts
- api/src/data/dataLoaders/company.ts
- api/src/data/dataLoaders/index.ts
- api/src/data/dataLoaders/productCategory.ts
- api/src/data/dataLoaders/tag.ts
- api/src/data/resolvers/product.ts
- api/src/data/types.ts
- api/src/db/connection.ts
Graphql resolvers were creating too many database calls. By using `dataloader` now it batches and caches database requests from resolvers.
> Optimize graphql resolver: Product

- ui/src/modules/settings/boards/components/Pipelines.tsx
- ui/src/modules/settings/boards/styles.ts
[Add sort option in the Sales/Task/Ticket/Growth Hacking pipelines list in the Settings #2974](https://github.com/erxes/erxes/issues/2974)
Sorting pipelines:
Searching in pipelines:
> Pipeline sort and search

- api/src/data/resolvers/tags.ts
- api/src/db/models/definitions/companies.ts
- api/src/db/models/definitions/deals.ts
- api/src/db/models/definitions/engages.ts
- api/src/db/models/definitions/integrations.ts
- Graphql resolver on `Tag.totalObjectCount` was running slow.
- Counting logic was also flawed. It was making duplicate counts in cases where descendant tags were assigned to the same document.
> Optimize resolver: `Tag.totalObjectCount`

- api/src/__tests__/boardQueries.test.ts
- api/src/data/resolvers/queries/boardUtils.ts
- api/src/data/resolvers/stages.ts
- ui/src/modules/deals/options.ts
- ui/src/modules/growthHacks/options.ts
- ui/src/modules/inbox/components/conversationDetail/workarea/WorkArea.tsx
- ui/src/modules/tasks/options.ts
- ui/src/modules/tickets/options.ts
[ISSUE]
1. Team Inbox Web hook section. When click web hook conversation, it will show Internal Note default.
2. Deals, Growth hacking, Tasks, Tickets. Filter section. When click Filter by created member, Filter by priority, Date range, itemsTotalCount shows wrong number. Fixed
> Conversation hook + Board filter number fix

- builder/commands/build.ts
Replace Dockerfile in build time when DockerFile exists in plugin-api.
> add Dockerfile replacer, when DockerFile exists in plugin

- packages/erxes-ui/src/components/filter/Filter.tsx
- packages/plugin-contacts-api/src/coc/utils.ts
- packages/plugin-contacts-api/src/graphql/company.ts
- packages/plugin-contacts-api/src/graphql/customer.ts
- packages/plugin-contacts-api/src/messageBroker.ts
- packages/plugin-contacts-ui/src/companies/components/list/CompaniesList.tsx
- packages/plugin-contacts-ui/src/companies/containers/CompaniesList.tsx
- packages/plugin-contacts-ui/src/customers/components/list/CustomersList.tsx
- packages/plugin-contacts-ui/src/customers/containers/CustomersList.tsx
- packages/plugin-segments-api/src/messageBroker.ts
- packages/ui-contacts/src/companies/graphql/queries.ts
- packages/ui-contacts/src/customers/graphql/queries.ts
- packages/ui-segments/package.json
- packages/ui-segments/src/components/filter/TemporarySegment.tsx
- packages/ui-segments/src/components/form/Form.tsx
- packages/ui-segments/src/components/form/SegmentsForm.tsx
- packages/ui-segments/src/containers/form/SegmentsForm.tsx
**Description**
This PR adds a temporary segment component that filters plugin data and saves it as segments.
**Type of PR**
This PR is an `enhancement`.
**Checklists:**
**How to use temporary segment component on new plugins:**
1. Add `a temporary segment component` in the plugin component that you want to use it.
2. Pass parameter named `segmentData` through query which you want to filter.
3. Use `segmentData` parameter in query builder function in API development.
**Screenshots:** 📸 📸 📸
> Temporary segment

- packages/plugin-ecommerce-api/src/graphql/resolvers/mutations/productreview.ts
- packages/plugin-ecommerce-api/src/graphql/schema/productreview.ts
- packages/plugin-ecommerce-api/src/models/definitions/productreview.ts
> ecommerce description & info add on api

- packages/plugin-payment-api/src/api/constants.ts
- packages/plugin-payment-api/src/api/socialpay/api.ts
- packages/plugin-payment-api/src/public/js/script.js
> fix socialpay deeplink

- packages/plugin-facebook-api/src/graphql/resolvers/queries.ts
- packages/plugin-facebook-api/src/handleFacebookMessage.ts
- packages/plugin-facebook-api/src/models/definitions/comment_conversations.ts
- packages/plugin-facebook-api/src/models/definitions/comment_conversations_reply.ts
- packages/plugin-facebook-api/src/store.ts
- packages/plugin-inbox-ui/src/inbox/components/conversationDetail/workarea/ActionBar.tsx
- packages/plugin-inbox-ui/src/inbox/components/conversationDetail/workarea/Post.tsx
> facebook-post-comment -conversions

- packages/erxes-ui/src/components/Uploader.tsx
- packages/erxes-ui/src/components/richTextEditor/RichTextEditorControl/MoreButtonControl.tsx
- packages/erxes-ui/src/components/richTextEditor/RichTextEditorControl/RichTextEditorColorControl.tsx
- packages/erxes-ui/src/components/richTextEditor/RichTextEditorControl/RichTextEditorHighlightControl.tsx
- packages/erxes-ui/src/components/richTextEditor/RichTextEditorControl/RichTextEditorImageControl.tsx
- packages/erxes-ui/src/components/richTextEditor/RichTextEditorControl/RichTextEditorLinkControl.tsx
- packages/erxes-ui/src/components/richTextEditor/RichTextEditorControl/styles.ts
- packages/erxes-ui/src/components/richTextEditor/TEditor.tsx
- packages/erxes-ui/src/components/richTextEditor/extensions/FontSize.ts
- packages/erxes-ui/src/components/richTextEditor/hooks/useExtensions.ts
- packages/plugin-inbox-ui/src/inbox/components/conversationDetail/workarea/Editor.tsx
- packages/plugin-inbox-ui/src/inbox/components/conversationDetail/workarea/RespondBox.tsx
- packages/plugin-inbox-ui/src/inbox/hooks/useDeboucedValue.tsx
- packages/ui-emailtemplates/src/components/Form.tsx
Resolved editor related issues & made some changes to inbox editor with RichTextEditor component.
> Fix editor issues

- packages/plugin-cards-api/src/graphql/schema/board.ts
- packages/plugin-cards-api/src/models/definitions/boards.ts
- packages/plugin-cards-ui/src/settings/boards/components/PipelineForm.tsx
- packages/ui-cards/src/boards/components/editForm/CloseDate.tsx
- packages/ui-cards/src/boards/components/editForm/Top.tsx
- packages/ui-cards/src/boards/graphql/mutations.ts
- packages/ui-cards/src/boards/types.ts
- packages/ui-cards/src/settings/boards/graphql/mutations.ts
- packages/ui-cards/src/settings/boards/graphql/queries.ts
SELECT THE DAY AFTER THE CARD CREATED DATE
> Cards pipeline fix

- packages/plugin-facebook-api/src/store.ts
> getOrCreateComment-function

- packages/plugin-facebook-api/src/store.ts
> Facebook post comment get or create comment

- packages/plugin-facebook-api/src/controller.ts
> console.log

- packages/plugin-facebook-api/src/handleFacebookMessage.ts
- packages/plugin-facebook-api/src/store.ts
> fix:(erxes:error Error occurred during callback inbox:sendNotifications Cannot read properties of undefined (reading '_id'))
